### ISSUE TITLE
write README

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#1]
This will cover all the usual README stuff, but should also (hopefully) capture all of the important bits of the design @aghisla and I put together. It should be detailed enough to act as a design document that Onyo can be developed from. Like a form of Documentation-Driven-Development.

**Comment by TobiasKadelka** [comment]
While the readme is not completely finished, I wonder if this issue can't be closed anyways, since we have a bunch of "design/implement function x" issues and the TODOs in the readme itself that are more specific?
