### ISSUE TITLE
impliment `onyo tree`

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#10]

**Comment by TobiasKadelka** [comment]
Works, but "onyo tree" does the same like "tree", even if not in git/onyo, so we might want to add additional checks/things instead of just doing exactly the same like the original tree.

**Comment by aqw** [comment]
Without knowing any specific problems... my general opinion is that the more similar `onyo tree` is to `tree`, the better

Is there anything specific that you think should be different?

**Comment by TobiasKadelka** [comment]
I spent time implementing something, that kind of was already there exactly like that, which made me assume that it was probably meant to do *something* different (e.g. just displaying the files/folders that are in onyo). But I am also happy to leave it like this. :)
