### ISSUE TITLE
BUG: `onyo rm/edit/set <uncommited>` can't fix the repositories state, because it fails fsck

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#107]
When using some commands (e.g. `onyo mv`), onyo will first perform an fsck and block commands when the fsck fails.

It was early on decided, that it should be possible to use onyo commands to fix a repositories state when the command is unambigous (e.g. `onyo edit`, `onyo set`, `onyo rm`).

This issue is closely related to #176, which proposes flags to (de-)activate checks manually.
I think we should define a list of checks that are run for each command by default first, and #176 should then be implemented to allow updating these lists.

My proposal for which checks should be run by default for each command:
- fsck runs all checks
- read only commands work always (tree, ls, get, cat, history)
- "fixing" commands work always, but just save correct assets (edit, set, rm)
  - they don't work e.g. with `onyo set --rename` on incorrect assets
- other commands work only on clean states (mv, config, mkdir, new)

I am wondering, if the last group should work on assets/dirs when they are completely valid and will stay so, e.g. `onyo mv` should work to move a valid asset into a valid folder, config when the config file is correct, new and mkdir always, because they can't damage a depository further?

**Comment by TobiasKadelka** [comment]
I updated this issue, and will begin to implement it soon if no contrary feedback is given, because I hate the current behaviour so much while testing, and I think it is helpful for #176 anyways.

**Comment by aqw** [comment]
In general, I agree with this. But the specifics of how this will work is unclear to me.

One of the checks onyo performs is whether the git repo is in a clean state. If the changes are unstaged, will onyo accidentally stage them? And if they're already staged, then `onyo set`, etc will fold those in with the current change.

I'm not sure if I see a significant difference between the "fixing" commands and the rest (except, arguably, `new`).
