### ISSUE TITLE
default value for `onyo set --depth NUM`

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#108]
Currently I have choosen 0 as depth, so by default one can add just real assets, so `onyo set RAM=10 shelf/` would be the same as `onyo set --depth 0 RAM=10 shelf/`, and thereby it would add no assets. However, to add the assets directly in that folder, one can do either `onyo set --depth 1 RAM=10 shelf/` or `onyo set RAM=10 shelf/*` so the question of this issue is not about functionality. Instead I want to make sure, that the default behaviour is intuitive.

So, alternatively, we might want to have a default of 1, so that when the user runs `onyo set RAM=10 shelf/` the assets directly in shelf will be added?

**Comment by aqw** [comment]
> Currently I have choosen 0 as depth, so by default one can add just real assets, so `onyo set RAM=10 shelf/` would be the same as `onyo set --depth 0 RAM=10 shelf/`, and thereby it would add no assets.

If this is silent, then I would view this as poor UX, and thus a bug.

`onyo set RAM=10 shelf/` should throw an error, and state that `onyo set` can only operate on assets unless `--recursive` is used (see also `--depth`).

`onyo set --depth 0 RAM=10 shelf/` feels like a no-op. Is there a valid use-case for setting a depth of `0`? If not, onyo should require that depth be `>=1` IMO.

`onyo set RAM=10 shelf/*` reads as valid to me, and is the same as `onyo set --recursive --depth 1 RAM=10 shelf/`. Which is fine. The question is: is `onyo` smart, and ignores all (non-asset) folders? Or do we use shell expansion straight, and then this command errors if it encounters a folder? Or warns but continues?

**Comment by TobiasKadelka** [comment]
This is example output for the described situations, and I think they align with your thoughts. 

When calling a folder, without --depth and without selecting assets, this is the error message:
```
❱ onyo set RAM=10 -s shelf
ERROR:onyo:
No assets selected. To add assets from directories use --depth [NUM].
```

When using `shelf/*`, the shell expands it and there is no need for depth:
```
❱ onyo set RAM=10 -s shelf/*        
onyo wants to update the following assets:
    shelf/laptop_apple_macbookpro.1
    shelf/laptop_apple_macbookpro.8
Update assets? (y/n)
```

When called with `shelf/*`, and shelf has a folder and an asset (and --depth is not used, so by default 0), onyo automatically ignores the folder and just lists the assets in shelf it wants to update:
```
❱ onyo tree shelf
shelf
├── folder
└── laptop_apple_macbookpro.1

1 directory, 1 file
❱ onyo set RAM=10 -s shelf/*
onyo wants to update the following assets:
	shelf/laptop_apple_macbookpro.1
Update assets? (y/n)
```

**Comment by aqw** [comment]
Great. The above largely sounds sane to me.

After reviewing the README, it seems that I intended `onyo set` to operate recursively by default (but I never state so explicitly).

I think there's a choice here:

1) commands operate recursively by default (i.e. if you pass a folder, you intend to operate recursively)
    - We assume the user knows what they're doing, and don't require a flag just because it's a folder.
2) require the `--recursive` flag
    - Commands commonly require a `--recursive` flag (with `--depth` to control). So we match a common idiom.
    - It allows situations like `onyo set RAM=10 shelf/*` to ignore folders easily
    - default `--depth` of infinity. Used to limit the depth of recursion.
    -  `-r` is already used for `--rename`; that doesn't conflict with `-R`, but it's close

**Comment by TobiasKadelka** [comment]
I added the recursive flag as -R, and when the flag is used by default the depth is infinite (the `--depth` flag does not have to be used to run onyo recursive, just to limit the depth if wished).
Users have to use the --recursive flag to use `onyo set` on directories, otherwise an error will be displayed. When the flag is not specified, by default the command is for assets. In any case, first a promt is displayed that lists the assets that would be modified and the user is asked to verify the list.

The user can add a value for --depth `> 0` (not `>= 0 `), otherwise an error appears.

Situations like `onyo set RAM=10 shelf/*`, when a folder contains multiple assets, but also folder `example_folder`, do this:
```
INFO:onyo:Can't set values for folder "shelf/example_folder" without --recursive flag.

onyo wants to update the following assets:
shelf/laptop_apple_macbookpro.8
shelf/laptop_apple_macbookpro.9
```

So it is mentioned, that the values will not be set for the folder, but it is just a warning and the assets selected by `shelf/*` will be listed and can be updated.

**Comment by aqw** [comment]
This sounds great to me. :-)
