### ISSUE TITLE
Add dictionary keys and initializing of lists to `onyo set`

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#114]
There are some functionalities described in the readme, which are not implemented or not tested.

From the old readme (should be added again, together with the implementation):

1.)
> Dictionary keys can be addressed
>  using a `.` (e.g. `parent.child`).

While I am not against this way of addressing dictionary keys, this would block a user from having a dot in key names and update these with `onyo set` in a situation like this:
```
slots.USB: 4
slots.lightning: 2
```

2.)
>  Key values can be initialized as a dictionary or list --- but only as empty.
>  - lists: `key=[list]` or `key=[]`
>  - dictionaries: `key=[dict]` or `key={}`

**Comment by TobiasKadelka** [comment]
I assume, an existing list should not just be initialized, but it should also be possible to empty it with `onyo set key=[]`?

**Comment by aqw** [comment]
> Dictionary keys can be addressed

Yeah, this is where things get fuzzy for me. Maybe `.` is a bad idea, and we should stay with `[]` and `{}`. I never fully grokked what we should do here. 

> I assume, an existing list should not just be initialized, but it should also be possible to empty it with `onyo set key=[]`?

Yes. I agree.

**Comment by aghisla** [comment]
Not sure if I am panicking in the right disco, but I see "parent.child" keys as a parallel solution to YAML's nesting by indentation, and I would not mix them, at least not in the asset file.

If we're talking about how to format options for `onyo get/set`, then I would need to give it more thought.
