### ISSUE TITLE
tree: checks cwd for onyo-repository, but not the path to display

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#121]
If outside of an onyo repository and using `onyo tree .` it gives an error that the directory is not onyo (as wished). But if inside an onyo repository, the user can e.g. do `onyo tree ..` to pass a path into the function which is not onyo, which will be displayed then without an error.

This is low effort to change, but also not imediately important, since onyo still just uses the classic `tree` command, without doing any color highlighting or anything else onyo specific. However, since there are ideas about making commands like `onyo tree` stronger in some form, this should at some point in the future be updated.

The solutions could be:
1. check for the directory to display correctly, not just if inside an onyo repository
2. remove checks in general and allow all paths to be passed into `onyo tree`, since right now there is nothing that would get lost, instead it would just allow the command to always work and be not onyo specific.

**Comment by aqw** [comment]
Ahh yes. Good point. `onyo` should ensure that any paths/arguments do not escape the repository. `git` does such checks.

```
(ansible) aqw@hrududu in ~/git/inm7/ansible on git:master!
❱ git status ../
fatal: ../: '../' is outside repository at '/home/aqw/git/inm7/ansible'
(ansible) aqw@hrududu in ~/git/inm7/ansible on git:master!
❱ git add -p ../
fatal: ../: '../' is outside repository at '/home/aqw/git/inm7/ansible'
```

This should be for all commands, and not just `onyo tree`.

**Comment by TobiasKadelka** [comment]
> This should be for all commands, and not just `onyo tree`.

I know, `onyo tree` is just the only command where that does not happen (as far as I could find) so far ;)
