### ISSUE TITLE
Commit messages for onyo commands should include the asset

### ISSUE THREAD

**Issue by aghisla** [psyinfra/onyo#122]
`onyo history` currently shows a list of terse "new asset|folder(s)." , and requires to open the details of each commit to know more about what happened.

It would be of more immediate use if commit messages of commands included the asset filename (or path) like:

- `onyo new`: "create new $type $asset-filename in $asset-folder"
- `onyo mv`: "move $asset-filename to $asset-new-folder"
- `onyo rm`: "delete $asset-filename from repository"

**Comment by aqw** [comment]
Absolutely! And I like each of the example strings suggested here. :-)

**Comment by TobiasKadelka** [comment]
This was the implementation in the beginning, and removed by request.

The main reason was (IIRC), that we allow for most commands multiple assets as input, and there was no clear thought on how to display e.g. the removal of 20 assets in the commit message, so it was proposed to move it all to the body of the commit message, not the head (which I think is also not fully/consistently happening).

So I think when a solution/decission is made how to handle very long lists (norm length and add something like "etc" or "..."? List always *all* assets in body, no matter how many already are in the message head) I will go through all commands and normalize the commit messages all together.
We want maybe also implement #90 with that (e.g. overwrite the message head, and list all assets in the body).

**Comment by TobiasKadelka** [comment]
Solved via the last merged PR.
