### ISSUE TITLE
DOC: divide README's contents in dedicated files and make it a summary with links

### ISSUE THREAD

**Issue by aghisla** [psyinfra/onyo#125]
The README is now functioning as both a development guideline and a go-to for testers, but it's getting impractical to navigate.

I suggest to relocate its contents (as they are) in separate files:

- `DESIGN.md`: Just Files and Folders, Inventory Concepts, Asset Name Scheme, File Contents, Config Files, Template Files, Field Validation, Environment Variables
- `COMMANDS.md`: Commands
- `EXAMPLES.md` Examples, Example Templates, Example Validation

Then put in the README only the following:

- a oneliner description of Onyo
- how to install it (pip in virtualenv, for now, for who doesn't have a preferred way to compile from source)
- links to the above mentioned files
- how to contribute (which can be a file on its own but doesn't need to be just now).

One more needed file is a quickstart that is a mix of what the examples are for now but in a way that one can use it as a small demo.

**Comment by TobiasKadelka** [comment]
Good point. Decissions gor this should be connected with the works in #2 and #17

**Comment by aqw** [comment]
Yeah, the current README is definitely unwieldy. We've been talking about using Read The Docs as well, and then the README would become much as you describe.
