### ISSUE TITLE
improve help text for onyo new --non-interactive

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#128]
Currently, it is not clear how `onyo new --non-interactive` is passed the necessary information to create a new asset.

**Comment by TobiasKadelka** [comment]
For documentation:

1.)
`echo "1\n2\n3\n4" | onyo new -I shelf/`

creates `shelf/1.2.3_4` and can also be called by other scripts.

2.)
To call it from python (e.g. the pytests):
```
import subprocess
import shlex

cmd = "onyo new --non-interactive shelf"
input_str =  "1\n2\n3\n4"
run_process = subprocess.Popen(shlex.split(cmd), stdin=subprocess.PIPE,
              stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)

run_process.communicate(input_str)
```

**Comment by aqw** [comment]
Sorry, I should have been more explicit: the help text does not make this clear.

**Comment by aqw** [comment]
Sorry, I should have been more explicit: the help text does not make this clear.
