### ISSUE TITLE
design how a "folder asset" will work

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#18]
(NOTE: there is debate about whether Onyo should be aware of this use-case, or whether a user crafted solution is sufficient).

It should be as similar as possible as the normal file-based use-case.

The folder must match the asset naming pattern, and the asset file within must also match it.

~~I am currently debating between an asset file names something simple like "asset" (I don't actually like "asset", but something simple like that) vs matching the folder name verbatim (which will likely complicate the `onyo mv` and `onyo set` commands).~~

**Comment by TobiasKadelka** [comment]
Since I am cleaning up the readme.md and it contains some "legacy thoughts" about folder assets, I will add these here. The open TODOs (designing, documenting and implementing) are:

- How to edit folder assets
- How to validate folder assets
- What is the file-name to describe the folder-asset?
   - server (tracked) and a NIC (tracked)
    - laptop (tracked) and software license (tracked)
- How to convert an asset file into an asset folder (e.g. when a license is given to it)

Additionally, from this Issue, I think the question comes up if/how we want to explicitly implement these functions, or if we just make it possible to give a folder a name following a name scheme.
In any case, I think this contains some aspects to discuss at a point in the future.

**Comment by TobiasKadelka** [comment]
The section, as removed by PR #91, for later design discussions:

> Advanced
> 
> A folder can also bundle multiple assets together into a larger asset, such as a server with a separately tracked network card, or a laptop with a specific software license.
> 
> TODO:
> 
>     what is the file-name to describe the folder-asset?
>         server (tracked) and a NIC (tracked)
>         laptop (tracked) and software license (tracked)
> 
> If licensing is attached to a particular machine (such as an OEM licence), then it is best encoded as a metadata field. If the license is transferable, then the laptop asset should be converted to a folder, and the license moved into it.

**Comment by TobiasKadelka** [comment]
Folder assets are currently just thought of, and there where talks to not implement them as a separate thing, but instead allow them implicitely. For now I remove the parts of the readme that mention them:

```
Just Files and Folders
[...]
A folder can also be used to bundle multiple assets
together into a larger asset (see "Advanced").
```

**Comment by aghisla** [comment]
I want to give this some more abstract thoughts and some actual tests with bundles of hardware that we consider as a unit but with parts that may be tracked separately by us or Admin. More comments to follow.

**Comment by bpoldrack** [comment]
Thinking about this, I'd like to suggest the following:

- Asset folders themselves have to follow the naming spec for assets (sort of obvious).
- The respective YAML could be stored in that folder under `.onyo-asset-dir.yml` or similar. `.onyo*` already is a "reserved namespace", the file can't be mistaken to be an asset on its own, the existence of such a specific file allows easy detection for onyo (whether or not a dir is an asset) and it's easy to exclude from anything dealing with the content of said dir.
- A regular asset can be auto-converted into an asset dir, whenever an asset is moved into it.
- More generally, think about it as both: a location and an asset. Not as a special asset.
- I suppose it would require a special flag for `new` and possibly a dedicated command to transform a regular asset into an asset dir and the other way around. I don't like that part yet, but with an auto-convert when it's a move target, it shouldn't be too inconvenient. May be we can still come up with a better idea of how to handle it interface-wise.

WDYT, @aqw , @TobiasKadelka , @aghisla , @nhjjr ?

**Comment by TobiasKadelka** [comment]
> Asset folders themselves have to follow the naming spec for assets (sort of obvious).

I agree in general, but am not sure if this actually always makes sense for the use cases (e.g. juseless would be a usecase I think). So probably before this gets actually implemented or defined there should be another issue very similar to your #345 :)

> The respective YAML could be stored in that folder under .onyo-asset-dir.yml or similar. .onyo* already is a "reserved namespace", the file can't be mistaken to be an asset on its own, the existence of such a specific file allows easy detection for onyo (whether or not a dir is an asset) and it's easy to exclude from anything dealing with the content of said dir.

In general it is not clear for me what would be stored in the respective YAML file at all. The idea of asset folders (IIRC) is to define an asset that has exchangeable parts with their own serial/inventory numbers.
 
I wonder (and I don't say I like the idea :P) if this could not be combined in some form with the `.anchor`, which is also already a "reserved namespace".

> A regular asset can be auto-converted into an asset dir, whenever an asset is moved into it.

This makes sense to me in theory. In practice I wonder if that would not be somewhat inviting errors or confusion. But I agree that having a way to later notice "it would be good if this asset had multiple separate parts" and act comfortably on it would be great. But if we want to have this happening automatically with a move, or with an additional flag (e.g. `onyo mv --make_folder_assets` or `onyo set --to_asset_folder` just to give badly named examples) is not clear for me.

> More generally, think about it as both: a location and an asset. Not as a special asset.

Definitely! 

> I suppose it would require a special flag for new and possibly a dedicated command to transform a regular asset into an asset dir and the other way around. I don't like that part yet, but with an auto-convert when it's a move target, it shouldn't be too inconvenient. May be we can still come up with a better idea of how to handle it interface-wise.

I agree, that we would probably want to have dedicated flags or commands for this.

---------------

All things considered, I do not disagree with your thoughts, but see a few very big problems with asset folders in general, which make it hard to comment on the issue.

1. we do not have any fully defined use case or workflow, just a few loose thoughts why this is needed.
2. onyo can not sum up similar values over multiple assets, e.g. if we would have a cluster bundeling up multiple servers, we could currently not even count CPUs or such things.

**Comment by bpoldrack** [comment]
@TobiasKadelka 

> In general it is not clear for me what would be stored in the respective YAML file at all. The idea of asset folders (IIRC) is to define an asset that has exchangeable parts with their own serial/inventory numbers.

Yes, but isn't the point that it is itself an asset? Hence, it got to have a YAML with it's own properties. Otherwise it would just be a location and no notion of an asset dir is required really. Or is your point that it only requires a serial number? Then my question would be: Do you think it reasonable to restrict all users to only assign the standard pseudo-keys to such assets, just because we couldn't come up with a case where we want more metadata on it? Is that a good enough reason to not allow more?

> onyo can not sum up similar values over multiple assets, e.g. if we would have a cluster bundeling up multiple servers, we could currently not even count CPUs or such things.

Well, yes and no. We can query for the values of a specific key for all assets in a folder. Summing the values can be done outside of onyo commands - both via CLI or python. Don't see a problem there. More generally: From my POV onyo needs to deliver the relevant metadata not interprete it (which is what we'd do if we say "oh, this value is a count"). This is up to the user and what they want to use the option for arbitrary key-value-pairs for.

**Comment by bpoldrack** [comment]
> "server exists and is in juseless, but not connected yet", where it would be an asset in the folder location-wise, but should not be considered part of the asset.

I see. I'd argue that this is smashing two different concepts into one another and needlessly complicating things.
If one wants to distinguish the notions of "at location" and "part of" then both need to be represented by different folders.
One could have:
```
|---juseless  # regular location folder
        |-- not_connected_asset  # regular asset file
        |-- juseless # asset folder whatever the name needs to be
               |-- .onyo-asset-dir.yml  # juseless' metadata
               |-- connected_asset # regular asset file
```

**Comment by bpoldrack** [comment]
Verdict from roadmap meeting for 1.0:

Go for asset folders with reserved name YAML file. No `.anchor` file in such folders. Have simple conversion command(s) for asset file <-> asset folder. Automatic conversion via `mv` or similar: Figure later, especially with respect to collapsing asset folder to file again.
Open question: Allow absence of `.anchor` or enforce absence?
