### ISSUE TITLE
Performance: use git index to list existing files in `get_list_of_assets()`

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#218]
The function `get_list_of_assets()` is extremly inefficient, and gets called many times (e.g. when creating a new file, when renaming a file, and probably also during some of `onyo fsck`s functions).
The inefficience is mainly caused through this call in a loop:
`run_cmd("git -C \"" + repo_path + "\" check-ignore --no-index \"" + elem + "\"")`

Instead there should be used the git index, which can probably already be called to list files with the python git implementation used in other functions.

**Comment by aqw** [comment]
I have encountered this numerous times in `onyo fsck`. I will address this as part of my work refactoring the command.

**Comment by TobiasKadelka** [comment]
I close this issue, because the git index is used since the merge #216, and your `onyo fsck` work also solves this.
If there is something that I am missing, feel free to open again.
