### ISSUE TITLE
design template matching system

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#22]
- How are applicable templates determined?
  - a list of string/regex patterns as the key and the value as the template name
  - "first matching template" the "winner?
    - the user must put them in the right "order"
  - alternatively: most specific name (CSS style) "wins"
    - feels intuitive, but these means building a scoring system --- complicated
      - pattern = 1 point per field
      - string = 10 points per field
      - tie breaker is the higher one in the list

**Comment by aqw** [comment]
Perhaps of use: https://docs.python-cerberus.org/en/stable/

**Comment by TobiasKadelka** [comment]
From the #7 about designing onyo fsck:

- validate the contents of all files against their respective templates

As soon as the template system is designed/implemented, onyo fsck needs a functionality to verify the correctness of templates, when:

- templates change
- files change

**Comment by TobiasKadelka** [comment]
To keep this issue up to date:
In #92 I ignored all the things above!

The current behaviour is this:
`onyo new --template laptop shelf` creates a new asset in the folder "shelf", it opens the current dialog from onyo new and asks for fields (including reserved characters), which are specified in the template file `.onyo/templates/laptop` (which is YAML). The flag expects the name of a file in that folder.

**Comment by aqw** [comment]
I think this can be closed now. Templates are specified by the user explicitly for a long time now, and I see no compelling reason to change that.
