### ISSUE TITLE
add type hinting and lint check for it

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#222]
`mypy` and `pytype` are linter options.

**Comment by TobiasKadelka** [comment]
Should this happen all at once for consistency, or should I do it stepwise (i.e. for the functions I am changing right now)?

**Comment by aqw** [comment]
IMO, this should happen naturally, as we move through the code.

But figuring which linter should be used (and how it will behave) is a prerequisite to that.

**Comment by TobiasKadelka** [comment]
We decided against `pytype`, but consider `pyur`

**Comment by aqw** [comment]
Reading this discussion makes it sounds like `pytype` does not follow the PEPs for typing.

https://news.ycombinator.com/item?id=27107647
