### ISSUE TITLE
DOC: logging/print overhaul

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#255]
The current proposed solution:

- commands only use `print()` (no logging)
- Classes and Methods only use `log` (no printing)
- CLI logging will use a custom formatter to remove the "onyo:INFO" (etc) prefix.
- CLI logging will split INFO level and print it to stdout. (https://stackoverflow.com/questions/1383254/logging-streamhandler-and-standard-streams)
- Logging default will be bumped up to warning, as per default.
- Child loggers will be created for each public method (e.g. `onyo.fsck`). This will be achieved using decorators (e.g. `@log('fsck')`) and applied to all related private methods, so that they all inherit the same log level.
- If a CLI wants its "own" method to have greater verbosity (for example: CLI `fsck` wants `Repo.fsck()` INFO level logging), then that will be set for that specific child logger.
- CLI `quiet` modes will either set the log level to CRITICAL or pass in a null logger handle

Once this is done, then the tests for commands can be overhauled, and they can focus on the user experience (exit codes, output, etc) and path handling, rather than functionality (which is well covered by the `Repo` tests).

**Comment by bpoldrack** [comment]
Referencing #386 here (point 4 - output design)
