### ISSUE TITLE
Argument Parsing Overhaul

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#260]
The current way we use the arg parser does not fullfill all our wishes when it comes to usage. This is especially true regarding the commands `onyo set key=value asset` and also `onyo new key=value asset`, other commands should follow these.
The most important part of this issue is the discription of the goal, which should, in the end, be reached. But the rest explains that I currently do something different, and which problems I had that lead me to this different approach.

The Goal:
- We want `onyo set key=value [key=value ...] asset [asset ...]` to automatically detect which inputs are key value pairs, and which are asset names, without having actual `--set` and `--asset` flags (which would otherwise be the easiest way). For `onyo set` at least one key value pair is needed, but assets are optional, the cwd or onyo root should be used as default. Both parameters (key value pairs and assets) are allowed to be lists of any length.
- We want `onyo new --set key=value asset` to have the optional flag `--set`, but also the possibility to not use it, while at least one (possibly multiple) asset(s) are needed, except when a `--tsv tsv.file` is specified, which disallows giving assets via command line.
- For both commands `onyo --help` should mention the parameters for key value pairs and assets.

The current approach:
- To automatically differentiate between key value pairs and assets, I use arg parser to take all of the "left over" arguments (at the end of the call, after optional other flags are interpreted) and just select the one with an `=` in it and manually set them, i.e. `setattr(namespace, "path", paths)` and `setattr(namespace, "keys", pairs)`, and afterwards check that both variables, `args.path` and`args.keys` are set correctly for the command (in the command itself, NOT with argparser like for the other commands).
- `onyo new`  has atm no `--set` flag, the same approach as above is used to automatically differentiate between key value pairs and assets, and the command checks the validity of the values, too.

The Problem:
- The current approach of automatically differentiating between inputs, and then checking the validity of the inputs in the command, works because I enter both inputs in argparser like they where just one type of argument. This means also that when `onyo --help` is called, just the one parameter known to argparser is listed.
- maybe this is practically a small thing for our use cases, but asset names with an `=` in them can lead to problems
- besides from the complexities introduced by having a mix of the standard usage of argparser and doing some manual work, the approach of just using 1 parameter (and differentiating manually) creates the need to having that parameter als non-optional (i.e. one or many inputs, not zero are allowed), so argparser wants to check the number and additionally we check the numbers of inputs (separately for key value pairs and for assets) in the command. Even adding the relevant parameters as optional (zero, one or many arguments) introduces problems (e.g for two lists of any length without flags dividing them it is not clear when which starts, especially in the case of `onyo new --set`).
- `onyo --set` is optional, so (following the point above) the list of assets would need to be the required parameter. But the list of assets is also optional, if a --tsv is given. This is why I currently have no --set, but just put all the arguments from the end of the command call (like for `onyo set`) into the function that then manually checks for `=` and sets valules, even if this is less intuitive and we want to have the `--set` flag. This could be solved e.g. with inspecting all the raw inputs and then either use if/else to decide how we build argparse (a terrible idea), or doing more things manually instead of with argparse, but even going this more costly road and trying to handle/catch all bugs does not solve the other problems mentioned.

**Comment by aqw** [comment]
Closing in favor of #286 and #287
