### ISSUE TITLE
DEMO: Update `onyo set` with filtering

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#266]
Currently, the demo does:
`onyo set -y USB_A=2 */laptop_*.* */*/laptop_*.*`

This is done to demonstrate how to update a value for all laptops in the inventory.
Later (after `onyo get` exists) the laptops should either be selected with a flag of `onyo set`, or with the usage of a subshell which calls `onyo get`.

**Comment by aqw** [comment]
Depends on #113
