### ISSUE TITLE
warn if there are untracked files in the repo

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#27]
I think Onyo should be opinionated about maintaining a clean repo.

If there are untracked files, it is likely:
- a user oops
- leftovers from an onyo oops
- a bad user decision that is a disaster waiting to happen

It also makes it harder to trust our assertion that file names are unique, as we use the git index to check that.

Onyo should check at the beginning of every invocation (unless we determine this is too expensive) whether the tree is clean. By warning /right away/, users should have a pretty good idea of /what/ caused it, and the git history will be helpful.

The user should use `.gitignore` for any intentionally untracked files in-repo. Silly users should be silly in a sane-ish fashion.

**Comment by TobiasKadelka** [comment]
If I understand this right, it would mean that an onyo-repo has to be either 100% onyo, and can't be a normal git repository with code or other stuff in it or at least if somebody would create a new file, since this would block onyo from working until all files are handled again?

**Comment by aqw** [comment]
No, that's not quite right.

If someone wants to store "non-Onyo" stuff in the repo, they have two options:
- commit the files (the content is now `tracked`)
- use `.gitignore` to ignore the files they're storing in the repo (in an uncommitted state)

What I am proposing is that Onyo should error when it encounters `untracked` files that are not ignored by `.gitignore`.

**Comment by TobiasKadelka** [comment]
With the implementation of #86 the user will be warned when using any (except read-only) `onyo <command>` in case there are changes which are not commited.

**Comment by aqw** [comment]
Will they be warned? Or will it error out? I /strongly/ prefer the latter.

**Comment by TobiasKadelka** [comment]
It will error out and specify the files causing problems, and how to solve them 👍
