### ISSUE TITLE
git mv <source folder> <existing_destination folder> can not overwrite <existing_destination folder>

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#29]
This is git-behaviour that I did not know (never thought about it):
When a folder ```user_a``` exists, but not ```user_b```: ```git mv <source> <destination>``` renames ```user_a``` -> ```user_b```.

When folders ```user_a``` and ```user_b``` both exist: ```git mv <source> <existing_destination>``` git does NOT rename, but move ```user_a``` -> ```user_b/user_a```.

Since onyo uses ```git mv```, this seems to make it impossible to overwrite one existing user-folder with moving another (in git and in onyo), even with --force and --rename flags activated. Do we want, that ```onyo mv``` is exactly like ```git mv```, or should this be different? (e.g. I could delete the existing destination folder and then do the move.)

**Comment by aqw** [comment]
`git mv` is just matching the behavior of normal `mv`. My first impulse is for `onyo mv` to match the behavior of `git mv` and `mv`.
