### ISSUE TITLE
Collect/Manage interactive functions of onyo

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#298]
We got over time a few different functions, that all are on the "interactive" front of onyo, and thereby not part of the Repo class. They do oftentimes overlap, and because of this and their interactive nature, we might want to solve these functionalities together.

The most notable of these functionalities are:
- `edit_asset()` in `edit.py`, which is possibly the only command using `os.system`
- `request_user_response()` in `edit.py`, which is the only function which is imported by other commands (currently just used by `new.py`, but later it should be used by all commands)
- using the `-m` flag without arguments to spawn an editor for manual editing of commit messages (currently not implemented, but we thought about it, and it would have to use `os.system`, too)

**Comment by bpoldrack** [comment]
I think this can be closed in this shape, due to #402
