### ISSUE TITLE
ambiguity in design of `onyo get`

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#30]
This likely affects other commands as well.

Currently, the readme describes the following syntax for `onyo get`:

> `onyo get [--depth num, -d] [--filter key=value[,key=value]..., -f] [--machine-readable, -m] [--sort-ascending key, -s | --sort-descending key, -S] keyname... [asset | directory]...`

The issue is: how is onyo supposed to distinguish between a `keyname` and an `asset | directory`? Put concretely, how should onyo determine the difference between the following situations?

```
onyo get key key key
```
```
onyo get key key directory
```
```
onyo get key directory directory
```
```
onyo get invalid_key directory directory
```
```
onyo get key invalid_directory directory
```
```
onyo get invalid_key invalid_directory directory
```
etc etc

The options I see are:
1) put `keyname` behind a required argument and make them comma delimited. For example:
  ```
  onyo get --keys key,key directory directory
  ```
2) Put `asset | directory` behind an optional argument and make them comma delimited. For example:
  ```
  onyo get -z directory,directory key key
  ```
3) Put `asset | directory` behind an optional argument. Argument must be called multiple times for multiple assets/directories. For example:
  ```
  onyo get -z directory -z directory key key
  ```
4) No arguments, Require that multiple keys are comma delimited. For example:
  ```
  onyo get key,key directory directory
  ```
  ```
  onyo get key directory directory
  ```
  ```
  onyo get key,key
  ```

My current favorite is option 4, as it follows the idiom setup by the `--filter` argument. Thoughts?

**Comment by TobiasKadelka** [comment]
Looks good to me, the PR fixes the problem of ambiguity 👍
