### ISSUE TITLE
BUG: `onyo init` prints into stderr on success

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#305]
This is a known problem, but I want to explicitely mention it here.
`onyo init` should on success print into stdout, but prints into stderr with an `INFO`.

When we solve #255 this should be solved, too, and the `onyo init` tests should be updated accordingly.

**Comment by aqw** [comment]
I have tested this with latest onyo (post `ui.py` work), and `onyo init` still prints to stderr.

The stderr output is the following:
```
(onyo) aqw@hrududu in /tmp
❱ onyo init yope 1> /dev/null 
INFO:onyo.git:Initialized empty Git repository in /tmp/yope/.git/
INFO:onyo:Initialized Onyo repository in /tmp/yope/.onyo
```

According to POSIX, `stderr` is about diagnostic output, not necessarily errors. Which has long been identified as open to interpretation.

For reference, `git` does the following with `git init`:

`stdout`:
```
Initialized empty Git repository in /tmp/yope/.git/
```

`stderr`:
```
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
```

I like the idea of matching git's behavior here, and not thinking too hard about this.

Which beings me back around to supporting this issue: we should indeed print these `onyo init` messages to `stdout`.
