### ISSUE TITLE
More complete `.onyo/` support

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#306]
The `.onyo` directory is quite important for a bunch of functionalities, and yet it feels incomplete.
This does contain a bunch of things I am repeatedly thinking about might be helpful (and which are currently uncomfortable to use).

- add `fsck` for fully populated `.onyo/`
  - replace `fully_populated_dot_onyo()` from `tests/commands/test_init.py` with a normal `repo.fsck()`
- add something like `onyo repair` command:
  - adds everything missing to `.onyo/`
  - adds `.anchor` to all directories
  - commits unsaved/uncommited changes
  - obviously all with "diff" to verify that nothing is done that should not be happening
- add tests to verify a damaged `.onyo/` does not mess up everything:
  - e.g. that `.gitconfig` is used when `.onyo/config` is missing
  - missing template folder does not crash, but instead mentions that the dir/template is missing
- enable easier template editing (remove some default fscks for `.onyo/`?)
  - `onyo new --path .onyo/templates/new_template` errors because `new_template` is no asset name
  - using an editor to create a new template forces user to `git add` and `git commit` manually
- https://github.com/psyinfra/onyo/issues/101

**Comment by TobiasKadelka** [comment]
In #308, when clearing caches, I often clear `Repo._templates` and bravely declare these might be changed by the commands. This is on ocasions a lie, but it does reflect the fact that, like described in this issue above, the missing abilities of onyo to change templates is in my opinion somewhere between missing feature and bug.

**Comment by TobiasKadelka** [comment]
I added the flexible name scheme issue regarding changable pseudo keys to the initial description of the issue.

**Comment by aqw** [comment]
I am closing this as this issue is largely covered by #599 and then the template topic is covered in #552.
