### ISSUE TITLE
design folder "anchoring"

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#31]
`git` does not track folders, but there are workflows where a folder should always remain, even if it is "empty" (i.e. does not contain any asset files). The usual way of doing this in git is adding an empty `.anchor` file inside of a folder.

Onyo users can do this manually, but it would be convenient if onyo itself formalized this.

One form this can take is:
- `onyo anchor`
- `onyo unanchor`
- extending `onyo ls` to mark "anchored" folders (perhaps highlight with a color?)

These commands need to be designed and added to the README.

**Comment by TobiasKadelka** [comment]
Should `onyo anchor --recursive <dir>` anchor all folders in a given <dir> tree?
For `onyo unanchor <dir>` it seems clear that it should remove all anchors in all folders under <dir>, but for creating anchors I am not sure.

**Comment by aqw** [comment]
> Should onyo anchor --recursive <dir> anchor all folders in a given tree?

Yes. I think that `onyo anchor <dir>` should create an anchor file in only `<dir>`, while `onyo anchor --recursive <dir>` should create an anchor file in `<dir>` and all dirs underneath it.

> For onyo unanchor <dir> it seems clear that it should remove all anchors in all folders under , but for creating anchors I am not sure.

I disagree. `onyo unanchor <dir>` should only remove the anchor file from `<dir>` and should leave decedents untouched. `onyo unanchor --recursive <dir>` should remove the anchor file from `<dir>` and all dirs underneath it.

**Comment by TobiasKadelka** [comment]
> > For onyo unanchor  it seems clear that it should remove all anchors in all folders under , but for creating anchors I am not sure.
> 
> I disagree. `onyo unanchor <dir>` should only remove the anchor file from `<dir>` and should leave decedents untouched. `onyo unanchor --recursive <dir>` should remove the anchor file from `<dir>` and all dirs underneath it.

Yeah yeah, I misstyped.... I meant `onyo unanchor --recursive <dir>` for unanchoring all subfolders.
Thanks 👍

**Comment by TobiasKadelka** [comment]
TODOs/Conclusion:
- add recursive flag to `anchor` and `unanchor`
- add recursive flags for both to README.md
- add to ls (#9) and tree functions to display the information (and also explanation into readme)

**Comment by aqw** [comment]
Ok. It sounds like we're in agreement about how this should look.

Unless you're already doing so, I can write this up and open a PR.

**Comment by TobiasKadelka** [comment]
Cool, don't hesitate :)

**Comment by aqw** [comment]
While writing up the `onyo anchor` and `onyo unanchor` commands, I became pretty convinced that exposing this idiosyncrasy of `git` to users is the wrong path to take, and that instead all directories should be anchored.

I see two paths:

## User-choice Anchoring

The user is made aware of the concept of anchoring, and why it is needed (`git`). Anchoring is not by default, and the user must mark folders as anchored/unanchored. 

The following new/changed commands are needed:

- `onyo anchor` (anchor a dir)
- `onyo unanchor` (unanchor a dir)
- `onyo anchors` (list all anchored dirs)
- colorize `onyo ls` / `onyo tree`
- already planned, but will need to become anchor-aware
  - `onyo mkdir`
  - `onyo rmdir`
  - `onyo rm`

## Anchor Everything

All folders are anchored. The Onyo repository behaves like a filesystem by default rather than a git repository.

The following new/changed commands are needed:

- `onyo empty` (list all empty dirs; normal unix commands won't work, as the dirs are not actually empty)
  - A better name is needed, as this can also be read as the verb "to empty". Alternatively, if `onyo get` is made aware of directories, then `empty` can be another pseudo-key.
- already planned, but will need to become anchor-aware
  - `onyo mkdir`
  - `onyo rmdir`
  - `onyo rm`
  - `onyo fsck` (check that all dirs have a `.anchor` file)

----

In either scenario, commands need to become anchor-aware. The question is whether any folders should ever be unanchored. If so, the user must be made aware of the concept of anchoring, and have mechanisms to query/visualize it (`ls`, `tree`, `anchors`, etc).

Thoughts?

**Comment by aqw** [comment]
Summary from our meeting: we are in agreement that "anchor everything" is simpler, and follows the principal of "just do the right thing by default".

Closing in favor of #58
