### ISSUE TITLE
Add specific Onyo exceptions

### ISSUE THREAD

**Issue by nhjjr** [psyinfra/onyo#316]
Some Onyo functions raise exceptions to indicate, for example, invalid user input. I suggest such cases to use a custom `OnyoException`. We expect these errors and want to provide a graceful error message (i.e., no trace and possibly formatted using `rich`). We can then use `try/except OnyoException`, rather than more ambiguous standard exceptions such as `ValueError`.

Case in point: `Repo._update_names()` updates asset names. It raises a `ValueError` if the new name is the same as the current asset name, and a `ValueError` if the name is invalid (i.e., `Repo.valid_name()` returns `False`). Here I propose using `OnyoNameError`. If we except a `ValueError`, other unexpected errors may sneak by, whereas errors of the type `OnyoException` are all expected and handled by us.

To do this, we should create a `class OnyoException(exception)` base class. Further custom errors, such as `OnyoNameError`, `OnyoInvalidRepoError`, or `OnyoProtectedPathError` then inherit from this class with their own custom messages. This also allows us to use `pytest.raises` more effectively in our tests.

**Comment by aqw** [comment]
Onyo now has a variety of Onyo-specific exceptions: https://github.com/psyinfra/onyo/blob/main/onyo/lib/exceptions.py

Closing. :-)
