### ISSUE TITLE
Consider changelog tooling

### ISSUE THREAD

**Issue by bpoldrack** [psyinfra/onyo#337]
I would like to suggest looking into utilizing tools for generating changelogs in order to make it a less time-consuming effort.
More specifically I'd suggest using [sriv](https://github.com/nedbat/scriv), which I have a nice experience with in the DataLad ecosystem.

The way this works is:
Whenever someone is creating a pull request, he'd locally run `scriv create`. This generates a template file underneath `changelog.d` with a generated name (based on timestamp and git identity by default). This file needs to be edited and committed within the PR.
When a release is prepared. `scriv collect` is being run and automatically assembles all the snippets from the PRs since the last release into a changelog.
Of course, templates, names, places, etc. can be configured and be somewhat dynamic:

Example from datalad:

config
```
❱ cat changelog.d/scriv.ini                                                          1 !
[scriv]
fragment_directory = changelog.d
entry_title_template = file: templates/entry_title.md.j2
new_fragment_template = file: templates/new_fragment.md.j2
format = md
# The categories must align with the category names in SEMVER_LABELS in
# tools/ci/mkchlog-snippet.py
categories = 💥 Breaking Changes, 🚀 Enhancements and New Features, 🐛 Bug Fixes, 🔩 Dependencies, 📝 Documentation, 🏠 Internal, 🏎 Performance, 🧪 Tests
```
template definition
```
❱ cat changelog.d/templates/entry_title.md.j2 
{{ version if version else "VERSION" }} ({{ date.strftime('%Y-%m-%d') }})
```
```
❱ cat changelog.d/templates/new_fragment.md.j2 
<!-- Uncomment the section that is right (remove the HTML comment wrapper).-->
{% for cat in config.categories -%}
<!--
### {{ cat }}

- Describe change, possibly reference closed/related issue/PR.
  Fixes [#XXX](https://github.com/datalad/datalad/issues/XXX) via
  [PR #YYY](https://github.com/datalad/datalad/pull/YYY)
  (by [@GITHUBHANDLE](https://github.com/GITHUBHANDLE))
-->
{% endfor -%}
```

Now, what you'd get from `scriv create` is something like this:

```
<!-- Uncomment the section that is right (remove the HTML comment wrapper).-->
<!--
### 💥 Breaking Changes

- Describe change, possibly reference closed/related issue/PR.
  Fixes [#XXX](https://github.com/datalad/datalad/issues/XXX) via
  [PR #YYY](https://github.com/datalad/datalad/pull/YYY)
  (by [@GITHUBHANDLE](https://github.com/GITHUBHANDLE))
-->
<!--
### 🚀 Enhancements and New Features

- Describe change, possibly reference closed/related issue/PR.
  Fixes [#XXX](https://github.com/datalad/datalad/issues/XXX) via
  [PR #YYY](https://github.com/datalad/datalad/pull/YYY)
  (by [@GITHUBHANDLE](https://github.com/GITHUBHANDLE))
-->
<!--
### 🐛 Bug Fixes

...
```

You fill in the pieces relevant for your PR and what is generated from this in the end is something like this:

https://github.com/datalad/datalad/blob/maint/CHANGELOG.md

**Comment by TobiasKadelka** [comment]
This looks good to me! Especially the datalad example convinced me, and the templates seem simple enough to modify, so as to apply it to our changelog-style! Thanks for looking into it and presenting the information here in such a clear way.

It also seems to me (correct me if I am wrong), that after collecting information (with `scriv create`), one has to manually select and edit sections, so it is easy for the person publishing a new release to adjust irregularities in phrasing across different PRs.

**Comment by aqw** [comment]
+1 from me as well. I find the example to be readable, and we can always edit the output.

The process for creating changelog snippets should be documented, as well as the release process.

Thanks for the suggestion!

**Comment by TobiasKadelka** [comment]
It seems to me like everybody agreed that this is a nice solution, and nobody used it.
We are currently very close to the next release, so this is not a point in time were we should begin to use any new tools, since the next changelog will have to be done by hand in large parts anyways; thereby I close this issue.

When sombody disagrees with me closing this now, or we decide in the future we want to use such a tool, feel free to re-open the issue again!
