### ISSUE TITLE
Extract asset functions from `Repo`

### ISSUE THREAD

**Issue by bpoldrack** [psyinfra/onyo#340]
Following up on #325, functionality in the `Repo` class, that is actually not about a Git repository, should be extracted into stand-alone functions. `lib/utils.py` seems like an obvious place to go for. The aim is, to have iterative refactoring. First, separate out what either doesn't need to be part of `Repo` or belongs to a non-repo notion (like "assets" in case of #325) and then see which of those functions are operating on the same kind of data and may form a new class. This should then help to clarify what exact notion/abstraction is actually needed.

**Comment by TobiasKadelka** [comment]
I want to point to this issue: #298
It is also about extracting some functionality, that did not belong into the repository class, but should also probably not live in the commands, so it might be considered together with the current effort :)
