### ISSUE TITLE
Separate git-init and Repo.__init__

### ISSUE THREAD

**Issue by bpoldrack** [psyinfra/onyo#346]
`Repo.__init__()` incorporating a possible initialization of an underlying physical repository is likely to cause increasing pain.
It's already leading to a somewhat strange behavior of `Repo`'s constructor, where the `init` flag implies the `find_root` flag but still both need to be set. It also does not account for the fact, that a repository may require re-initialization. (See discussion in https://github.com/psyinfra/onyo/pull/334/files#r1178829398).
This already shows part of the problem, which is that path handling logic is different for those two purposes. Ultimately, creating a repository on FS and instantiating an object representing such a repository are two different tasks, that should be done by different functions. That does not preclude to do both from an API point of view. Several `Repo.from_X()` methods are thinkable, that could serve as convience w/o entangling those two things and w/o restricting access to `git-init` calls (private `Repo._init()`).

Point in case: We did the same thing in DataLad and it turned into a major annoyance. Although, admittedly it's a bit more complicated when git-annex comes on top, but the issue is the same in principle.

**Comment by TobiasKadelka** [comment]
@bpoldrack do you know if this issue was already solved with functions like `maybe_init()` and  the logic in `git.py`, or do these functionalities still need to be devided like described by the issue?

**Comment by bpoldrack** [comment]
The separation is addressed indeed. I'd like to also reconsider the `init` and `find__root` flags eventually, but it's sort of a different topic. Hence, closing.
