### ISSUE TITLE
`onyo new --help` uses ambiguous term "location"

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#35]
`onyo new --help` provides the following output:

```
❱ onyo new --help
usage: onyo new [-h] location

positional arguments:
  location    Directory to add the new onyo asset

optional arguments:
  -h, --help  show this help message and exit
```

"Location" could mean either file name or directory. The description does clarify that it is a "directory", but the same language should be used throughout. The commands defined in the README always use "directory" rather than "location".

**Comment by TobiasKadelka** [comment]
The help was updated in f0eca7e36a13c89e4441df5a70adf74db47c57f6
