### ISSUE TITLE
Redesign file system like commands `onyo tree`, `onyo cat`, `onyo ls`

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#352]
These commands are directly related to the standard file system commands, and currently simply parse paths and then call the normal `tree` and `cat` commands (`onyo ls` would presumably do the same, but is not even implemented yet). The biggest difference is currently that those commands run some onyo fscks, but technically they offer nothing that could done e.g. with a normal `cat` call.

There are some ideas, how to make these commands more valueable:
- color for different outputs of these and all other commands #55 
- `onyo cat ASSET > NEW_ASSET` could function as "copy the contents from ASSET into a NEW_ASSET if fscks don't fail or something like this
- `onyo tree` could be rewritten in python, instead of calling the tree command, and then we could for example remove `.anchor` files, mark non-inventory files, all things that fail `onyo fsck` or some other things like this

**Comment by aqw** [comment]
Closing, as this covers a variety of issues rather than one, and both `cat` and `tree` are now python implementations (and so will any potential implementation of `onyo ls`).

Individual feature requests are tracked in other issues. Anything missing can be opened in a new issue.

Closing.
