### ISSUE TITLE
exclude subtrees for `get`

### ISSUE THREAD

**Issue by bpoldrack** [psyinfra/onyo#359]
`get` should probably have the means to exclude subtrees (such as an `retired` or `lost` folder) from queries.

Usecase from #345 would be a query for devices with a manufacturer recall.

**Comment by TobiasKadelka** [comment]
This should be done together with an implementation of:
- https://github.com/psyinfra/onyo/issues/259

**Comment by aqw** [comment]
Duplicate of #518
