### ISSUE TITLE
passing a filename to `onyo new` results in suboptimal error message

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#36]
If I pass a filename to `onyo new` (see #35), it provides a suboptimal error message:
```
❱ onyo tree
/tmp/tst
└── groups
    └── dp
        └── aqw
            └── laptop_lenovo_T490.abc123

3 directories, 1 file

❱ onyo new groups/dp/aqw/laptop_lenovo_T490.abc123 
ERROR:onyo:mkdir: cannot create directory ‘/tmp/tst/groups/dp/aqw/laptop_lenovo_T490.abc123’: File exists
```

This error message does state what is wrong (the file exists), but it doesn't tell the user what's /really/ wrong: that `onyo new` only accepts a `directory` as an argument and not a `file`.

**Comment by TobiasKadelka** [comment]
The error above was caused in part by the (now discarded) function of automatically creating a folder with `onyo new` when a folder does not exist. Since we now have `onyo mkdir` to do that and do not automatically created folders, the situation changed, and the error output is modified:

```
ERROR:onyo:/Users/tkadelka/new-onyo/second_tests/onyo_tests/test_1/no user/laptop_apple_macbookpro.8 is not a directory.
```
