### ISSUE TITLE
Properly define desired history

### ISSUE THREAD

**Issue by bpoldrack** [psyinfra/onyo#360]
Implementing #357, it became clear that there aren't a lot of meaningful assertions about what the history should look like yet.
There are two angles on this:
- what should be recorded and how (tied to existing issues about commit messages - https://github.com/psyinfra/onyo/issues/296 and the already closed https://github.com/psyinfra/onyo/issues/295)
- what should `onyo history`'s output look like

Ultimately, the aim should be to make an assessment of what happened to an asset (or location) in terms of inventory operations/onyo commands. Obviously, that can be found out, but it's not too obvious and easy ATM.
I moved a user and the commit looks like this:

```
commit 8766e5dad69899ad2b0082a6358d62eb6c1318b7
Author: Benjamin Poldrack <benjaminpoldrack@gmail.com>
Date:   Wed May 31 15:18:42 2023 +0200

    mv [2]: 'Sam User','laptop_lenovo_thinkpad.SN123Z' -> 'somegroup'
    
    somegroup/Sam User
    somegroup/Sam User/laptop_lenovo_thinkpad.SN123Z
```
I don't think it's super clear what happened here. The recorded paths don't actually add any information that isn't in the `mv ...` part (and in the commit itself) already. On the other hand there's no indication of where something was moved from. Furthermore, the real operation here was to move the user. Can a user easily tell, that this is what happened? And how much effort is it, to convey that to someone doing an audit?

Exact same issue obviously when a member changed their name. From the commit message - despite putting redundant info in there - it is indistinguishable from a record of a member switching workgroups.

So, one thing is what and how to record in the message and the other thing is how to show the history in an easily interpretable way from an "inventory POV", rather than a "git expert POV".

**Comment by TobiasKadelka** [comment]
In the initial description of this issue, I added the two issues about commit message header and body (and removed your TODO for this).
