### ISSUE TITLE
Allow "summing up" of `value`s with the same `key`

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#363]
Short example:
- When two assets both have `USB_C: 2` we want to be able to have a command or query that gives the sum as a result, in this case something like `onyo get --sum ASSET_A ASSET_B` should result in `USB_C: 4`.

1. This is IMO a strong requirement to have asset folders like discussed in #18. If there is no way to sum up multiple values, for example the number of CPUs of multiple servers bundled up in one cluster (which is then the asset folder), then the whole idea of asset folders does not help, but instead isolate information from each other.
2. This might also be interesting to find out how much storage a group folder contains or similar casees, were you do not care about in which file something is, or if it is used in 1 or 5 laptops, like the information currently provided by `onyo get`.  

Possible problems (which stop us from just looping over a list and summing up values) are obviously:
- How to handle this for values were it does not make sense to sum up numbers (e.g. dates, boolean)
- Values with units (e.g. `8GB`).
- How to handle empty values (e.g. `RAM: ""`, `RAM: `)
- Values which are not possible to sum up at all (e.g. `USB: 2` and `USB: yes`)

Implementation-wise, I can see this being used at least in 2 different situations:
- `onyo get --keys RAM --sum <group_a>` to get the RAM of all devices in group_a together
- `onyo cat <asset_dir>` to automatically sumerize all YAMLs in an asset folder as if it would be one asset file (hence the problem if e.g. two files contain a string defining an inventory number or other conflicts)

(I could imagine that for values that are not possible to sum up, we would just use lists to concatenate these into lists? ping #23)

**Comment by bpoldrack** [comment]
As mentioned in https://github.com/psyinfra/onyo/issues/18#issuecomment-1571492258, I'm not sure we should bother really. This boils down to interprete the meaning of particular keys:

> How to handle this for values were it does not make sense to sum up numbers (e.g. dates, boolean) ...

And that's not our business, I'd argue. It's the user who decides what keys to put in there and how to interprete them.
We can already provide a list of the values that would need summing via `get`. What's missing is better ways to format `get`'s output (not including the asset path in this case): See #358 
Summing them up can be done outside onyo.

**Comment by aqw** [comment]
The proper way to do this is to pipe onyo output into another tool. The user can choose from a variety of tools that will meet their needs (including addressing the type of corner cases that Tobias listed), any of which will be infinitely more capable than anything we could (reasonably) add to Onyo itself. 

For example:
```
❱ onyo get --keys path type ram --path jsc | awk '{ sum += $3 } END { print sum }'
22528
```

I will close this, as I believe both Ben and I are both strongly on the same page. @TobiasKadelka if you disagree, please re-open and we can discuss further. :-)
