### ISSUE TITLE
Clean up exception logging

### ISSUE THREAD

**Issue by bpoldrack** [psyinfra/onyo#365]
There's a common pattern:

```
if some_condition:
    log.error("message")
    raise SomeException("message")
```
This is not a good idea for several reasons.
Exceptions should be logged when they are handled (caught via `except`) not when they are raised. Especially when the message passed to the exception is the same that is being logged. Moreover, it's almost always used to communicate to a user. But a piece of code that raises an exception does - by definition - not know or care what the caller does with the exception. Hence, it's the wrong place to message to the user or even just decide whether there's a user message needed.
Also, since #343 most exceptions would bubble up to `main` anyway, be caught there and used for an error message, which means that with the above pattern we now get the message twice.

Remove those log messages. At some point we might figure that a few of those places deserve a DEBUG log giving some technical information (rather than a user facing error message), but that's a different topic.

**Comment by TobiasKadelka** [comment]
See also https://github.com/psyinfra/onyo/issues/255 about the logging and print overhaul.
