### ISSUE TITLE
`onyo mv` of an asset results in a suboptimal error message

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#37]
When I attempt to `onyo mv` a file to a new file name without the use of `--rename` (see also #38), it results in the following error:
```
❱ onyo mv groups/dp/aqw/laptop_lenovo_T490.abc123 groups/dp/aqw/laptop_lenovo_T490.abc1234
ERROR:onyo:laptop_lenovo_T490.abc123 -> laptop_lenovo_T490.abc1234 no renaming allowed.
```

The error message is vague, and merely states "no renaming allowed". Renaming of what? I can successfully rename directories, so I think onyo means that onyo assets are not allowed to be renamed without the use of the `--rename` flag.

A more helpful message would be to error, stating that onyo assets should not be renamed in normal operation. If you need to change one of the `type`, `make`, `model`, or `serial` fields, you should use the `onyo set key=value` command. If you know what you're doing and want to rename the file anyways, you can force the rename by using the `--rename` flag.

**Comment by aqw** [comment]
I like this message much better.

The only thing that I note as missing (which is a matter of taste), is the note about `onyo set key=value `.

Just my 2 cents. Overall it LGTM.

**Comment by TobiasKadelka** [comment]
For future reference I created a comment in #15 to add this when implementing `onyo set`. For now I will not add it to the output, to not confuse users when onyo will be tested.
