### ISSUE TITLE
Why fail on existing directories with mkdir?

### ISSUE THREAD

**Issue by bpoldrack** [psyinfra/onyo#371]
The respective piece of code is currently in `lib/onyo.py:OnyoRepo.mk_inventory_dirs`.

This is failing when it is called with directory paths that already exist. However, `Path.mkdir` is called `parents=True, exist_ok=True`. Furthermore, already existing anchor files apparently are not a reason to fail.

I wouldn't know why we'd want to fail on this condition. If (some) of the dirs exist - fine. Nothing to do.
Any objections to remove that condition?

**Comment by TobiasKadelka** [comment]
I am fine with changing this, though @aqw implemented this, and might know a reason why it does/should behave like this.

**Comment by aqw** [comment]
I was not familiar with that function name and had to look it up. It looks like a wrapper around `mkdir`.

Maybe this is a leftover from the idea that `onyo mkdir` should return non-zero if the destination exists. But `mkdir -p` returns 0 even if the destination exists. And `ony mkdir` imitates it. So..... that's a long way of saying: I see no need (from the CLI at least), to throw anything here.

**Comment by bpoldrack** [comment]
Ok, will remove it then and make it behave like `mkdir -p`.
