### ISSUE TITLE
Explain tsv-file format for help-text of `onyo new --tsv`

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#395]
This came up in https://github.com/psyinfra/onyo/pull/390#discussion_r1270313311
> This should include a description of what the TSV is supposed to look like (don't know from the top of my head).

This should include the required columns:
| type | make | model | serial | directory |

And mention that optional columns can be given as:

| key |
| value1 |
| value2 |

This is the read the docs page of onyo new, explaining the current table format under the example section:
https://onyo.readthedocs.io/en/latest/cmd_new.html#example-usage

**Comment by bpoldrack** [comment]
Note, that as of #403, there's `template` and `is_asset_directory` as well.

**Comment by bpoldrack** [comment]
Ping #486
