### ISSUE TITLE
design `onyo unset`

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#4]
This is for removing keys entirely.

This is functionally the same as `onyo set key=[unset] asset_file`.

**Comment by TobiasKadelka** [comment]
After designing this, it should be added to code and readme.
I will remove the TODO from the code for the time in between.

**Comment by TobiasKadelka** [comment]
From readme about `onyo set`:

> See `onyo unset` to remove keys.

I assume the unset command should completely delete a key from an asset, and also have similar flags like `onyo set` has, so recursive, quiet, yes, filter, depth, dry-run, etc.
The output also should be as similar as possible to `onyo set`.
Dictionary-keys and lists, too, should be similar where ever possible, though here I am not completely sure about how it should be used.

`onyo unset` should not be able to delete the pseudo keys of an asset name.

**Comment by aqw** [comment]
> I assume the unset command should completely delete a key from an asset, and also have similar flags like onyo set has, so recursive, quiet, yes, filter, depth, dry-run, etc.

> onyo unset should not be able to delete the pseudo keys of an asset name.

Yes, to both. :-)

**Comment by aghisla** [comment]
Not only be prevented from deleting pseudo keys, but also required keys #110.

**Comment by aqw** [comment]
> Not only be prevented from deleting pseudo keys, but also required keys #110.

More broadly, this is about validation. Commands which change the contents (`onyo set`, `onyo unset`, etc) or location (`onyo mv`, etc) will need to validate the changes before writing to disk. `unset`ing "required" fields would fail validation.
