### ISSUE TITLE
`onyo init` fails in an existing git repo

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#40]
According to the README, `onyo init` can be run on an existing git repository.

> [...] The directory will be initialized as a git repository (if it is not one already), the `.onyo/` configuration folder created, and template files generated and committed. [...]

However, the following fails:
```
❱ mkdir /tmp/tst
❱ cd /tmp/tst
❱ git init
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint:   git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint:   git branch -m <name>
Initialized empty Git repository in /tmp/tst/.git/
❱ onyo init
ERROR:onyo:/tmp/tst is already a git-repository.
```

**Comment by TobiasKadelka** [comment]
That it again prints "succesfully initialized the onyo repo" should not happen. Should it print a warning/info/nothing instead?

**Comment by aqw** [comment]
I think you're missing the point of the bug report.

The README states that the user can run `onyo init` on an existing git repository. This is currently not the case. Onyo errors instead, and does not create a `.onyo` folder.

```
❱ ls -lah
total 48K
drwxr-xr-x  3 aqw  aqw  4.0K Mar 18 11:16 .
drwxrwxrwt 23 root root  36K Mar 18 11:16 ..
drwxr-xr-x  7 aqw  aqw  4.0K Mar 18 11:16 .git
❱ onyo init
ERROR:onyo:/tmp/tst is already a git-repository.
❱ ls -lah
total 48K
drwxr-xr-x  3 aqw  aqw  4.0K Mar 18 11:16 .
drwxrwxrwt 23 root root  36K Mar 18 11:16 ..
drwxr-xr-x  7 aqw  aqw  4.0K Mar 18 11:16 .git
```

**Comment by aqw** [comment]
> I think for now I will print an info if already is onyo and git, but print a warning if it is already git, but not onyo, and still create an .onyo folder.

Sorry, I just saw this (since it was edited).

This is still not quite correct.

If the dir is empty:
  - init git and onyo
  - print success

 If the dir contains a git repo but not onyo dir
  - print information about presence of git repo
  - init onyo
  - print success

 If the dir contains both git and onyo dirs
  - print error (not warning)

 If the dir contains an onyo dir but not a git repo
  - It is unclear to me what the appropriate action is here. Onyo cannot get to this situation on its own, and the user has clearly been futzing around. Options are:
    - error
    - print a warning, and git init + git commit
