### ISSUE TITLE
DOC: help text for `onyo new` needs an example

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#408]
The correct usage for `onyo new` is not clear.

It took me a bit to realize that `-p` is  necessary to pass a destination directory as an argument.

```
❱ onyo new --edit haha/This\ \&\ That/                                                     
usage: onyo [-h] [-C DIR] [-d] [-v] [-q] [-y] <command> ...
onyo: error: unrecognized arguments: haha/This & That/
```

**Comment by bpoldrack** [comment]
Actually, `-p` should be optional, defaulting to CWD.

Also: Usage above is #356. Actual help on `new`:
```
❱ onyo new --help                                                                                                              2 !
usage: onyo new [-h] [-t TEMPLATE] [-e] [-k KEYS [KEYS ...]] [-p PATH] [-tsv TSV] [-m MESSAGE]
...
```
However, it does fail to mention, that CWD is the default and that specifying the `directory` key via `--keys`, `--tsv` or `--template` is an alternative (allowing to address different directories for bulk creation).

**Comment by bpoldrack** [comment]
Ping #486
