### ISSUE TITLE
BUG: removing a key used in the filename via `onyo edit` results in ERROR

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#412]
If I remove a key used in the filename, an (unhelpful) error is thrown.

Contents:
```
❱ onyo cat dp/Alex\ Waite/headphones_sennheiser_SR27.faux 
type: headphones
make: sennheiser
model: SR27
serial: faux
```

I then use `onyo edit` to remove the `serial` field.
```
(onyo) aqw@hrududu in /tmp/yope on git:master
❱ onyo edit dp/Alex\ Waite/headphones_sennheiser_SR27.faux 
Changes:
Save changes? No discards all changes. (y/n) y
ERROR: Command '['git', 'commit', '-m', 'edit: dp/Alex Waite/headphones_sennheiser_SR27.faux\n\n--- Inventory Operations ---\nModified assets:\n\t- dp/Alex Waite/headphones_sennheiser_SR27.faux\n']' returned non-zero exit status 1.
```

This is in contrast to `onyo new` which provides a meaningful error message and prompts me to re-edit:
```
❱ onyo new --edit
ERROR: Asset missing value for required field 'serial'.
```

The upshot is that Onyo does the right thing on error. The exit code is `1`, the edited file is unmodified, and the repository is completely clean, with no commit or staging.

**Comment by bpoldrack** [comment]
This actually closely related to #411. Issue being: validation upon `edit` is done in the wrong spot.
