### ISSUE TITLE
`onyo new` does not handle spaces correctly

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#42]
The README does not disallow spaces for the `type`, `make`, `model`, and `serial` fields (and perhaps it should). But `onyo new` handles spaces poorly. An example:

```
❱ onyo new groups/dp/aqw    
<type>*:laptop
<make>*:With an absolute path, a unix local named pipe is used for control. The file is created with user and group that is configured and access bits are set to allow members of the group access. Further access can be controlled by setting permissions on the directory containing the control socket file. The key and cert files are not used when control is via the named pipe, because access control is via file and directory permission.
<model*>:T490
<serial*>:abc123
ERROR:onyo:fatal: pathspec 'an' did not match any files

❱ onyo tree
/tmp/tst
├── a
├── absolute
├── access
├── access.
├── allow
├── an
├── and
├── are
├── be
├── because
├── bits
├── by
├── can
├── cert
├── configured
├── containing
├── control
├── control.
├── controlled
├── created
├── directory
├── file
├── file.
├── files
├── for
├── Further
├── group
├── groups
│   └── dp
│       └── aqw
│           └── laptop_With
├── is
├── key
├── local
├── members
├── named
├── not
├── of
├── on
├── path,
├── permissions
├── permission._T490.abc123
├── pipe
├── pipe,
├── set
├── setting
├── socket
├── that
├── the
├── The
├── to
├── unix
├── used
├── user
├── via
├── when
└── with

3 directories, 54 files

```

**Comment by TobiasKadelka** [comment]
I wrote a fix that will allow for spaces in all fields (and create just 1 file in the right location), but I think, at least when added as last/first character of the file name, I should still trim them.

**Comment by aqw** [comment]
I disagree about the trimming. Shell already splits on white space, so file arguments will already be trimmed. /If/ Onyo receives a file with a leading or trailing space, it's because the user explicitly asked for it using quotes or escaping with `\`. In such cases (and as always), we should do what the user asks. They may be silly, but we should not make it impossible to be silly when explicit.

**Comment by TobiasKadelka** [comment]
While the line `onyo new groups/dp/aqw` gets interpreted by CLI, this dialog:
```
<type>*:laptop
<make>*:With an absolute path, a unix local named pipe is used for control. The file is created with user and group that is configured and access bits are set to allow members of the group access. Further access can be controlled by setting permissions on the directory containing the control socket file. The key and cert files are not used when control is via the named pipe, because access control is via file and directory permission.
<model*>:T490
<serial*>:abc123
```

happens inside of `onyo`, so with the fix spaces are allowed, and one can add for each field as many spaces as wished, without escaping them explicitely, and this includes add the beginning and end of the name.

I searched a bit for ways to encode/decode these fields as if they are read by the CLI, but found nothing that really works so far.

That said, I will remove the trimming of whitespace, and since the bug actually described in this issue is solved (with next PR) I will open a new issue for the decoding.
