### ISSUE TITLE
BUG: `onyo mv`ing a dir into a nonexistent dir results in (odd) error

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#421]
The source directory exists, but none of the destination directories exist. I do think that `onyo` should error here, as the parents do not exist. Onyo does error, but the message printed is incorrect/doesn't make sense.

```
(onyo) aqw@hrududu in /tmp/yope on git:master
❱ onyo mv dp/Alex\ Waite does/not/exist/
ERROR: Cannot rename /tmp/yope/dp/Alex Waite -> /tmp/yope/does/not/exist. Consider moving instead.
```

vs

```
❱ onyo mv dp/Alex\ Waite/ does/not/exist/Alex\ Waite/
ERROR: Destination is not an inventory directory: /tmp/yope/does/not/exist
```

**Comment by bpoldrack** [comment]
Linking #420, since this is essentially the same problem
