### ISSUE TITLE
FEATURE: filename from stdout when using `onyo new`

### ISSUE THREAD

**Issue by nhjjr** [psyinfra/onyo#428]
Expected behavior:
```
ASSET=onyo new -k type=lorem make=ipsum model=dolor serial=faux
onyo set key1=sit key2=amet -p $ASSET
```

When creating a shell script to populate an inventory it is impossible to know what `serial=faux` comes up with, since `faux` creates a random value. It is common to use this in the asset's filename to prevent duplicate names. By providing the newly created asset's name to stdout, this can be captured and used in subsequent commands. 

Note that technically the keys in `onyo set` can be used in `onyo new`, there will be future commands for which this is not possible.

**Comment by bpoldrack** [comment]
Just a note: This requires a dedicated output mode, since nothing other than generated asset paths must be in stdout in this case. So, a switch that implies a form of `--quiet` (which itself implies `--yes`).

**Comment by TobiasKadelka** [comment]
We have `onyo get --machine-readable`; this needs to be overhauled still, but `--machine-readable` (maybe in UI.py too?), might be related, and these ideas should be considered together with your issue https://github.com/psyinfra/onyo/issues/358.

**Comment by aqw** [comment]
If it's just about being able to see the file name, then this is currently addressed by the content diffs. And #656 will make it even more obvious.

However, for the idea of programmatically extracting this information, we've long considered adding additional pseudo keys such as `date_created` and `date_modified`. If we had that, then one could:
```
onyo get -H --keys path -s date_created | head -n 1
```

To me, this feels like something that is flexible and can be used many ways. Whereas adding a feature specifically to `new` would only be useful in that one particular use-case.

I will open an issue for that functionality.

**Comment by aqw** [comment]
I am closing this in favor of #662 

If you disagree, please feel free to reopen and make your case. :-)
