### ISSUE TITLE
DOCS: Error message from duplicate template keys is unclear

### ISSUE THREAD

**Issue by nhjjr** [psyinfra/onyo#436]
When a template has duplicate keys the resulting error is both vague (to an Onyo user) and refers to documentation from a dependency.

Template:
```
---
rating: foo
rating: bar
```

Output when using `onyo new`:
```
ERROR: while constructing a mapping
  in "/home/niels/code/onyo-demo/.onyo/templates/boardgame", line 2, column 1
found duplicate key "rating" with value "foo" (original value: "bar")
  in "/home/niels/code/onyo-demo/.onyo/templates/boardgame", line 3, column 1

To suppress this check see:
    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys
```

**Comment by bpoldrack** [comment]
@nhjjr : What would you regard as "more useful information"?

The error says exactly what's wrong and where from my POV. I don't know what's vague about it.
This:

> To suppress this check see:
>    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

is admittedly a bit annoying and would be nicer to just swallow, but other than that I don't know how to improve upon 

> in "/home/niels/code/onyo-demo/.onyo/templates/boardgame", line 2, column 1
found duplicate key "rating" with value "foo" (original value: "bar")
  in "/home/niels/code/onyo-demo/.onyo/templates/boardgame", line 3, column 1

**Comment by nhjjr** [comment]
The error itself is pretty clear, as it uses terminology consistently used in onyo and references the (problematic) file. The main problem is the advice on how to suppress the check. Not only is that impossible within the context of onyo, it would be unclear to someone not familiar with the code or the dependency being used and possibly allude to functionality within the API (that isn't actually there).

**Comment by bpoldrack** [comment]
Ok. Agree on that aspect.
