### ISSUE TITLE
FEATURE: Expand template functionality

### ISSUE THREAD

**Issue by nhjjr** [psyinfra/onyo#439]
It seems useful to me to have templates not only provide default keys and values, but to also enforce what these values should look like. For example, including a `rating` key for which the values are forced to be integers between 1 and 10 (or None when undefined). 

In addition, beyond pseudo-keys some other keys might be required. For example, if the "owner" key is very important and should not be forgotten when adding or editing an asset, the template could have `owner: required`.

This is a low priority issue.

**Comment by aqw** [comment]
IMO, this is not something that should be enforced by the template, but rather validation (#256).

**Comment by nhjjr** [comment]
> IMO, this is not something that should be enforced by the template, but rather validation (#256).

That works for me, as long as the functionality is available somewhere. However, a "template" is something that shows me how to create an object from it, which includes the limitations and requirements of object properties. It is at the least semantically fitting.
