### ISSUE TITLE
minor hint: mv command with --help hint improvement

### ISSUE THREAD

**Issue by j-leo** [psyinfra/onyo#445]
using onyo mv --help tells me in order to rename a file I have to use onyo set, but IRL using onyo edit also works AFAIK

this is a very minor thing

**Comment by bpoldrack** [comment]
True and should be pointed out.
This leads to another small-ish issue, though: `set` does have a `-r` flag while `edit` doesn't. They should both do the same IMO.

**Comment by bpoldrack** [comment]
> This leads to another small-ish issue, though: set does have a -r flag while edit doesn't. They should both do the same IMO.

Verdict: Nope. `edit` is intentionally different and does not need that safeguard.

Hence, documentation is all that's to do here.
