### ISSUE TITLE
onyo set --help: required key defaults

### ISSUE THREAD

**Issue by j-leo** [psyinfra/onyo#449]
onyo set --help teaches me that the default requiered key are type, make, model and serial, but is that not subject of onyo config to change?

What I mean is, is this comment hard wired? Or does it read onyo config what the actual defaults are?

**Comment by bpoldrack** [comment]
Your suspicion is right: It's still hardcoded, while it's not actually fixed anymore.
The doc should reference the `onyo.assets.filename` config instead.
