### ISSUE TITLE
Document new configs in onyo-config's help

### ISSUE THREAD

**Issue by bpoldrack** [psyinfra/onyo#456]

**Comment by aqw** [comment]
What are the new configs that need documenting?

**Comment by TobiasKadelka** [comment]
I have already done parts of this in https://github.com/psyinfra/onyo/pull/540, at least for the readthedocs page https://onyo.readthedocs.io/en/latest/configuration.html and through adding an example in https://onyo.readthedocs.io/en/latest/cmd_config.html

However, the docstring from `onyo/commands/config.py` that gets parsed on top of https://onyo.readthedocs.io/en/latest/cmd_config.html is not up to date. That list needs to be adjusted.
