### ISSUE TITLE
BUG: onyo set faux serial

### ISSUE THREAD

**Issue by j-leo** [psyinfra/onyo#460]
As far as I experienced, onyo set cannot set/generate a new faux serial number.

OK, that might only be useful if a serial was given wrongly/by accident during creation of the asset, but now the object actually should not have a real serial (any more)

**Comment by aqw** [comment]
I think this is a duplicate of #413. @j-leo can you please verify?

**Comment by j-leo** [comment]
confirmed duplicate - closing
