### ISSUE TITLE
BUG: move and rename leads to unhelpful/incorrect error message from `onyo mv`

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#478]
When trying to move a dir from a sub-dir and renaming the dir at the same time, I get a message to "consider moving instead". I did consider moving, because I did use `onyo mv` and gave it a valid dir and a destination, so the message does not fit the situation.
```
> onyo mv admin/Karl\ Krebs/ Karl

ERROR: Cannot rename /Users/tkadelka/none-existing-folder/admin/Karl Krebs -> /Users/tkadelka/none-existing-folder/Karl. Consider moving instead.
```

P.S.: I did not see this exact issue so far, but there are many mv and output related issues, so sorry if this is a duplicate.

**Comment by aqw** [comment]
I believe this is a duplicate of #426. Can you look and verify?

**Comment by TobiasKadelka** [comment]
Thanks, this is correct. Will close this one.
