### ISSUE TITLE
Tests + docstring for onyo_tree

### ISSUE THREAD

**Issue by bpoldrack** [psyinfra/onyo#495]
Properly document `onyo/lib/commands.py:onyo_tree` and provide tests in `onyo/lib/tests/test_command_tree.py`.
Based on that reworked docstring, provide a respective command line version in `onyo/commands/tree.py`.

**Comment by aqw** [comment]
This was completed long ago as part of moving the functionality from system `tree` to a Python implementation. 

The doc strings are good, and the tests are sufficient.
