### ISSUE TITLE
design `onyo rm`

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#5]
To delete assets from the repository.

This should allow filtering, prompt by default, and be verbose. The `--quiet` and `--yes` flags should be available.

**Comment by aqw** [comment]
Thinking about this more... I wonder whether `onyo rm` should support filtering (in the style of `key=name`), or if we shoudl suggest that people use a subshell, such as:
```
# delete all laptops
onyo rm $(onyo get --filter type=laptop filename)
```

I'm unsure whether I find this to be clunky or beautiful. ;-)

**Comment by TobiasKadelka** [comment]
I think, at least from the use cases I can make up for onyo, that the "normal" way of rm with wildcard characters would translate quite well into `onyo rm`.
So it might make sense and be more handy to do this type of deleting with subshells. I will think about it further.

**Comment by aqw** [comment]
> I think, at least from the use cases I can make up for onyo, that the "normal" way of rm with wildcard characters would translate quite well into onyo rm.

That approach is useful (and one I think we should support)l, but is limited to filtering only the `type`, `make`, `model`, or `serial` keys (as those are the only ones exposed in the filename). Expanding this to other keys would require that either `onyo rm` gain knowledge of filters (a la `key=value` syntax) or we make sure that other commands (such as `onyo get`) can return the filenames in a format appropriate for consumption by `onyo rm`.

**Comment by TobiasKadelka** [comment]
I could see potentially more value in doing it in a working format with `onyo get` (possibly with a flag, otherwise always), since this would be also a nice feature in combination with other commands like `onyo mv`.

**Comment by aqw** [comment]
I envision `onyo get` as being a very machine-friendly interface, so we should make it handle this situation well.

There is a "TODO" in the Readme to list "pseudo-keys". This is information about an asset that is not in the asset-file itself. This includes information from the file-name (`type`, `make`, etc), but also will extend to git metadata (`created_time`, `modified_time`). It should also expose the filename/path in a format that is useful for commands such as `onyo rm`.
