### ISSUE TITLE
Finish git base

### ISSUE THREAD

**Issue by bpoldrack** [psyinfra/onyo#502]
This is about finishing the reliance on git and the `GitRepo` class.

Most importantly, the current code base still has a mixture of accounting for tracked files only vs. checking what's in the worktree. It should be the former everywhere (except to-be added paths, ofc).
This should involve a re-evaluation of cache(s), that are mostly unused ATM. We (likely) don't need staged and untracked files in properties. If tracked filles are the only thing to be cached, things should be easy - `commit` is the only thing to ever trigger a cache invalidation. Nothing outside `GitRepo` needs to care.

Also: `stage_and_commit` needs to take paths and only ever stage untracked ones. current `commit` should go entirely.

**Comment by TobiasKadelka** [comment]
FTR: The caches were in the past used for cases when files were generally tracked by onyo, but modified with external tools e.g.:
- a tracked asset gets moved/renamed with a classical unix `mv`, calling onyo commands afterwards might lead to a problem or commit an "illegal" (for onyo) change
- somebody edits a file, afterwards uses an onyo command on it (e.g. `onyo mv`), now the changes might be accidently commited when not content-checks are run
- a directory is created with unix `mkdir`, something is moved/added to it, and it gets added without `.anchor`

Of course these situations should be catched or evaluated at different points, and `onyo fsck` and validation will come back, and the caches are not necessarily needed for those checks. But when somebody removes these caches/concepts, it needs to be concidered that the functionalities are actually replaced, and not just currently ununsed.

**Comment by bpoldrack** [comment]
Not really. We don't commit whatever is staged/modified anymore. We do all changes in memory and commit the paths we know were affected by the operations. Whether there are other things is largely irrelevant for functioning. Hence, I don't think those properties will be needed.
Moreover, if/when we want/need to make sure there's nothing else (via `fsck` or during operation execution), we'd need an assessment of what's the case right now. Caching these would be an anti-feature.

However, whether and where such checks may be appropriate needs to be part of this effort - I agree.
