### ISSUE TITLE
Add `--exclude` option to `onyo get`

### ISSUE THREAD

**Issue by bpoldrack** [psyinfra/onyo#518]
The get command needs a way to specify what subtree(s) to not look at.
So, add an `--exclude` option that takes paths and possibly allow `--include` as an alias for `--path`.
`--depth` would still only apply to `--path/--include` and have no effect on `--exclude`. So, both are different ways of limiting what's included as opposed to `--depth` also limiting an exclude.

**Comment by aqw** [comment]
See also #359
