### ISSUE TITLE
BUG: calling `onyo rm <dir> <dir> <dir>` multiple times with same dir leaves git unclean

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#519]
This issue is about calling `onyo rm a/ a/`, but the problem should be considered together with `onyo rm a/b/ a/` (e.g. different paths are given, but the call would on disk try to delete the same destination twice)!

The bug is that I can call `onyo rm` multiple times with the same input and onyo even begins running the command, but then errors and leaves the git tree unclean.

```
❱ onyo rm admin admin admin                                                              130 !
The following will be deleted:
-/Users/tkadelka/onyo/admin/Karl Krebs/laptop_apple_macbookpro.9sdjwa
-/Users/tkadelka/onyo/admin/Karl Krebs
-/Users/tkadelka/onyo/admin
-/Users/tkadelka/onyo/admin/Karl Krebs/laptop_apple_macbookpro.9sdjwa
-/Users/tkadelka/onyo/admin/Karl Krebs
-/Users/tkadelka/onyo/admin
-/Users/tkadelka/onyo/admin/Karl Krebs/laptop_apple_macbookpro.9sdjwa
-/Users/tkadelka/onyo/admin/Karl Krebs
-/Users/tkadelka/onyo/admin
Save changes? No discards all changes. (y/n) y
ERROR: [Errno 2] No such file or directory: '/Users/tkadelka/onyo/admin/Karl Krebs/.anchor'
```

Basically, when I call the command like this, it seems to work  (e.g. a diff is presented because all paths are "possible to delete" -> no error).  But then onyo tries to execute, and errors --- presumably during the second deletion when it tries to delete the already-not-existing-anymore file.

This causes the problem that the command stops in between executions, which means the commit is not executed and the git tree is afterwards unclean:

```
❱ git status                                                                             130 !
On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    admin/.anchor
	deleted:    admin/Karl Krebs/.anchor
	deleted:    admin/Karl Krebs/laptop_apple_macbookpro.9sdjwa

no changes added to commit (use "git add" and/or "git commit -a")
```

Would we actually want to allow this type of szenario (and how we would like to handle sub-paths e.g. `onyo rm a/b/  a`)? We can either allow it and make sure it does not fail on such calls, or disallow it, and then error correctly: 

Dis-allowing:
1. check input paths for duplicates/sub-paths in the beginning and error if duplicates are found. 

Allowing:
1. de-duplicate the paths before deleting anything.
2. check before deleting again if the path does actually still exist. 

Technically it would also be possibly to find a solution that just reverses/restores changes or fscks/commits them afterwards if such an error occours, though I find these solutions always problematic. IMO just deciding to allow/dis-allow this behavior and then either add appropriate checks or errors should be fairly straight forward and lead to the best behavior.

**Comment by bpoldrack** [comment]
Note: Another flavor of #546.
