### ISSUE TITLE
`onyo_tree()` docstring lies about its default value

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#522]
The CLI call `onyo tree` (without specifying paths) does automatically use the CWD, but the python implementation does require an argument for `paths`, otherwise it errors with `TypeError: onyo_tree() missing 1 required positional argument: 'paths'`.

However, the python implementation states:
```
    paths: list of Path
        The paths to directories for which to print the directory tree.
        If no path is specified, prints the directory tree for CWD.
```

This is additionally problematic, because it is not obvious to me that the python function would be called from the "correct" directory, so IMO one cannot just add `paths: list[Path] = [Path.cwd()]` as a default to the function to make it work.

Since the function is called as `onyo_tree(inventory)` I feel like the most reasonable path to print by default for the python implementation would be the root of the inventory. However, I do not like the idea that the default behavior when not specifying a path is different for the CLI and the python function.

Alternatively, one might also just except the current behavior of the function, and delete the un-true comment about the CWD.

**Comment by bpoldrack** [comment]
> This is additionally problematic, because it is not obvious to me that the python function would be called from the "correct" directory, so IMO one cannot just add paths: list[Path] = [Path.cwd()] as a default to the function to make it work.

I don't see the problem really. However, I agree with the solution because of this:

> Since the function is called as onyo_tree(inventory) I feel like the most reasonable path to print by default for the python implementation would be the root of the inventory.
