### ISSUE TITLE
Test in inventory operations that keys are not illegally empty

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#535]
Issue in reference to: https://github.com/psyinfra/onyo/pull/529#discussion_r1499348157

The comment mentions that the inventory operations itself should check for empty fields or white space and RESERVED_KEYS/PSEUDO_KEYS, instead of the functions like set/unset.
1. I agree fully on the empty/white space checks, they should happen in the operations, and I will work on that soon.
2. for "RESERVED_KEYS and PSEUDO_KEYS" I don't think that is fully true, and would argue these need to be checked by the calling function above, not the operations. Technically we allow at least the name-fields to be changed with `--rename` and possibly with `onyo edit`. To do this on the lower level would probably require additional flags or context, and checking these allowed cases above seems to me currently being reasonable.

**Comment by bpoldrack** [comment]
FTR: I don't grasp the second point.

What do `RESERVED_KEYS` and `PSEUDO_KEYS` have to do with naming keys?
How is any of them being empty different from other keys being empty?
IMO, nothing that is written to the YAML should be an empty value.
I don't know, why you think:

> To do this on the lower level would probably require additional flags or context
