### ISSUE TITLE
BUG: `mkdir` sometimes prints paths multiple times

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#538]
While running the example command from https://onyo.readthedocs.io/en/latest/cmd_mkdir.html I noticed:
Creating sub-dirs with mkdir is possible, parent directories are created automatically. When multiple sub-directories are created for a not-yet existing parent dir, the parent dir (`/Users/tkadelka/onyo/marketing` in the example shown below) is printed multiple times in the diff output:

```
> onyo mkdir --message "the marketing group joined\!" marketing/Alice\ Wonder/ marketing/Karl\ Krebs
The following directories will be created:
+/Users/tkadelka/onyo/marketing/Alice Wonder
+/Users/tkadelka/onyo/marketing
+/Users/tkadelka/onyo/marketing/Karl Krebs
+/Users/tkadelka/onyo/marketing
Save changes? No discards all changes. (y/n)
```

This is functionally correct and does not lead to errors, but works exactly like the mkdir-call should. Just the output should be adjusted to remove the second mentioning of the "marketing" directory.

**Comment by bpoldrack** [comment]
Related: #546
