### ISSUE TITLE
Consider to allow non-inventory dirs

### ISSUE THREAD

**Issue by bpoldrack** [psyinfra/onyo#548]
I don't have a concrete usecase, but I stumbled upon this while addressing #519 and checking recursive directory removal:
We could allow for plain dirs (no `.anchor`) that therefore are not inventory-tracked items. This would be valid if they only contained `.onyoignore`'d files, so: no assets or inventory dirs underneath.

Low priority, though, just something to consider when we have some experience with `.onyoignore` usecases to begin with.

**Comment by TobiasKadelka** [comment]
Good news, this was already implemented at some point since the issue was opened! We currently have `bin/` without an `.anchor`; the dir is listed in `.onyoignore`, and onyo continues to work just fine.

I will thereby close this issue now, feel free to reopen it in case I missed something :)
