### ISSUE TITLE
colorize output of commands

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#55]
Everybody in the group agrees, that a bunch of our commands will profit from colorized output, so I want to edit this issue into a collection of ideas which can later function as a to-do list:

- `onyo tree` and `onyo ls` (and possibly paths in onyo fsck and onyo get):
  - assets (either file or dir) 
  - non-inventory files
  - failed fsck

- `onyo cat` and `onyo get`
  - different colors for different data types like int/str etc could help highlight inconsistencies
  - if validation is added, keys/values that fail validation

- `onyo fsck`
  - we parse information from `git status`, which has different colors for staged/unstaged files, but thanks to the parsing we loose these colors. I hate it and oftentimes use `git status` instead of `onyo fsck` because even this little color here is so helpful for quick glances!

**Comment by aqw** [comment]
Removed the "anchored" vs "unanchored" concept.

**Comment by TobiasKadelka** [comment]
I completely butchered and edited all the information in the original post of Alex to this issue, because our ideas of how onyo should act and what commands can provide became so much clearer.

**Comment by aqw** [comment]
This issue is overly broad.

I have opened a PR to bring syntax highlighting to `onyo cat` (#700).

`onyo tree` is colorized now, ever since I rewrote it in Python.

The rest of the commands either won't be implemented (`onyo ls`) or would not benefit from colorizing (`onyo get`).

Closing.
