### ISSUE TITLE
Dedicated `template` command?

### ISSUE THREAD

**Issue by bpoldrack** [psyinfra/onyo#552]
#461 suggests a dedicated `template` command.
This would involve creation of templates (including from existing assets), editing, removal, etc.

Personally I don't think there's much value in that, since there's nothing special about template files - all standard tools for creating, modifying, etc. files are fine and they can be committed w/o any operations record, etc.

However, the jury is still out - let's wait for some experience to see what may need some convenience WRT handling templates.

**Comment by aqw** [comment]
Closing in favor of #673 and #675
