### ISSUE TITLE
`onyo edit` should allow aborting without saving

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#553]
Let's say I edit an asset, make a change, but decide I don't want to keep it:
```
onyo edit accounting/Bingo\ Bob/headphones_apple_airpods.uzl8e1
Effective changes:
--- /home/aqw/git/inm7/onyo demo/accounting/Bingo Bob/headphones_apple_airpods.uzl8e1
+++ /home/aqw/git/inm7/onyo demo/accounting/Bingo Bob/headphones_apple_airpods.uzl8e1
@@ -1,4 +1,4 @@
-type: headphones
+type:
 make: apple
 model: airpods
 serial: uzl8e1
/home/aqw/git/inm7/onyo demo/accounting/Bingo Bob/headphones_apple_airpods.uzl8e1 -> /home/aqw/git/inm7/onyo demo/accounting/Bingo Bob/None_apple_airpods.uzl8e1
Accept changes? (y/n) 
```

I respond `n` that I don't want to accept the changes, but then it takes me back into my editor. An "abort" option would be nice, rather than needing to ctrl-C.

Proposed prompt:
```
Accept changes? (y)es (n)o (a)bort
```

Or alternatively
```
Accept changes? (y)es / (e)dit again / (a)bort and discard changes
```

**Comment by bpoldrack** [comment]
Agree. Was annoyed by this, too.

**Comment by bpoldrack** [comment]
https://github.com/psyinfra/onyo/blob/main/onyo/lib/commands.py#L316 suggests a similar but different TODO:

Adding a discard option, that would only affect the current asset. So it's skipping this asset proceeding with the next one instead (if there's any).
WDYT, @aqw - is this good enough or would want 4 answers (accept, edit, skip, abort)?

**Comment by aqw** [comment]
>  WDYT, @aqw - is this good enough or would want 4 answers (accept, edit, skip, abort)?

I like your 4 answer idea. 
- `accept` (accept and continue)
- `edit` (let me retry this asset)
- `skip` (screw this asset, but I want to keep what have done with previous assets and continue with the rest)
- `abort` (I just want to start over and leave this mess behind)

**Comment by TobiasKadelka** [comment]
The most minor thought possible, but just as an alternative word, instead of "(e)dit" I want to propose `(c)ontinue editing`. "edit" and "e" is the command and the flag of `onyo new`, so I like using the word "continue" to differenciate :)
