### ISSUE TITLE
install instructions insufficient

### ISSUE THREAD

**Issue by j-leo** [psyinfra/onyo#569]
When I try to install Onyo like described in the README, it tells me it needs python. 
My installed version is Python3.11.2. The next step is activating the venv. This one fails for me with `zsh: command not found: python
`. 

Then I tried to follow the link `installation instructions`:
I shall need python, tig and a few others. Those are installed. Next step is the pip install. beeep, error: `zsh: command not found: pip
`

Of course I know how to install it then, but I think the instructions should be more clear for newbies.

**Comment by j-leo** [comment]
if somebody else is reading this, surprisingly the solution was
```
alias python=python3
sudo apt install pip
```

**Comment by j-leo** [comment]
Nontheless this warning is not encouring after using the pip-install method:
```
Installing collected packages: onyo
  DEPRECATION: onyo is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
```
It provides the impression that the user sis something wrong.

**Comment by aqw** [comment]
Thanks for reporting these!

I have created #574 to track the installation warning from `pip`.
