### ISSUE TITLE
`onyo init` commits staged changes

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#571]
`onyo init`ing a directory with contents largely leaves them unaffected. If it's not a git repo, onyo init's, and only commits the `.onyo` dir.

If it is a git repo, we use it. If there are untracked or tracked changes, onyo ignores them.

However, if the git repository has something changed, onyo will include that in its initialization commit.

While in many ways I view this as the user's fault, I struggle to see a use-case, and it becomes "onyo's fault" since it's included in our commit.

I think `onyo init` should check for staged changes and error, telling the user to unstage or commit their changes.

And if the use /really/ was to combine their changes into onyo's commit, that is what  `git rebase` is for.

**Comment by TobiasKadelka** [comment]
This issue made me wondering if we should not have a prompt for `onyo init`, too.
Of course erroring works also, but your description underlined to me that this is indeed the only "committing" command that has no prompt.
