### ISSUE TITLE
Documentation example does not match repo example

### ISSUE THREAD

**Issue by nhjjr** [psyinfra/onyo#584]
The `.onyo/templates/laptop.example` does not contain the same keys as are listed on the [documentation](https://onyo.readthedocs.io/en/latest/configuration.html) page.

**Comment by TobiasKadelka** [comment]
Good point, the keys should be added to the file  `onyo/skel/templates/laptop.example` in the onyo repository´ because what the documentation describes makes most sense as a template example.
