### ISSUE TITLE
`onyo get` needs to differentiate between different none-value cases

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#588]
`onyo get` needs to allow to query, and display differently:
1.  key exists but without value
2. key does not exist at all

**Comment by bpoldrack** [comment]
We currently don't allow empty values. So we don't need to be able to query for that.
Not existing keys can be queried via `<unset>`:
`onyo get --match dne=<unset>`

As of now, this is documented in get's help.
