### ISSUE TITLE
`onyo_tree()` uses weird tuple for `dirs`

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#606]
The `onyo_tree` function accepts a tuple `(str, Path)` for `dirs`.

This is in contrast to how other commands accept paths. The `str` is to show the user the directories they called, in the format they called it.

This avoids loads of complexities with relative vs absolute paths, and CWD that is not repo-root.

Questions are (non-exclusive of each other):
- should `onyo_tree` print always relative to repo root
- what other commands are candidates for this tuple-approach
- is there a better solution than these tuples

**Comment by aqw** [comment]
@bpoldrack @TobiasKadelka Not sure if I captured your suggestions/thoughts well here. Please add them to help clarify what you two see.

**Comment by bpoldrack** [comment]
Registering the idea of `PathParameter` class, that allows to capture that sort of annotation (currently `description`). `onyo_XXX` could potentially accept both `Path` or `PathParameter`. Constructor would take a `Path` and an optional annotation (implementing a default ofc). This class could behave like a `Path` and only overwrite its `__str__` to make use of the annotation. So, for any actual path operation code doesn't need to change and only when calling `str()` on it there would be an effect.

**Comment by aqw** [comment]
I experimented with subclassing `Path` (which, as an aside, was not possible prior to 3.12) and simply overriding its `__str__` donder to return the string that it received when instantiated.

I now believe this approach is not a good one.

My approach was something like:

```python
class PathParameter(Path):
    def __init__(self, p: str, *args, **kwargs) -> None:
        self._original = Path(p, *args, **kwargs)
        super().__init__(p, *args, **kwargs)

    def __str__(self) -> str:
        return str(self._original)
```

And this mostly works. The `self._original = Path(p, *args, **kwargs)` is where things get fun.

Imagine the following code:
```python
print(path / self.ANCHOR_FILE_NAME)
```

The `self.ANCHOR_FILE_NAME` is passed as an arg to `path`, and it bubbles up all the way to `__init__`, creating a new object for `print`.  So capturing those args is important. Check.

Except lets consider the following:
```python
p = PathParameter(d).resolve()
```

This does not return `Path()` that is `.resolve()`ed. Rather `.resolve()` returns a new `PathParameter` that was instantiated with the resolved path. Now we have lost `d`, which was the entire point. After reading the pathlib source, I do not see a trivial way to wedge our desired functionality into `resolve()` (not to mention other functions that behave similarly).

Simply adding an attribute is the next logical solution. However, it fails the `path.resolve()` scenario for the exact same reasons.

Even if it is possible to override this cleanly, I have objections:
- loads of functions will need their type annotations adjusted
- all the new objects created will carry this thoroughly irrelevant information
  - the point here isn't waste, it's rather: that these objects are used for tons of path traversal. Onyo will check `Path(/)` at some point, and it would still carry this inane `self.original`. It's so irrelevant that it's dangerous.

I explored using `PathParameter` at only the CLI level and into `onyo_tree()`. From there on, everything would be converted into `Path`s. Perhaps a bit wasteful, but really not that bad given all the object creation going on anyway. Except `path.resolve()` rears its head again. We resolve all paths at the CLI layer, before passing into the `onyo_*()` functions. And I strongly believe this is the right thing to do.

The only two viable paths I see are:
1) keep using the tuple
2) create a non-pathlike object that carries the "description" and the resolved path object. `onyo_tree()` will accept either `Path` or this bespoke type.

**Comment by TobiasKadelka** [comment]
Uff, thanks for your work, this seems to have been a tough quest.

Reading through this, I think the best course of action is 1., and to just continue to live with the situation of the tuple.

**Comment by bpoldrack** [comment]
Thanks for the research! I should have realized that `resolve` does return a new object, ofc, since it needs to make it a concrete path and resolve against actual FS.
However, I still think this is solvable.

> My approach was something like:
>```
>class PathParameter(Path):
>   def __init__(self, p: str, *args, **kwargs) -> None:
>      self._original = Path(p, *args, **kwargs)
>        super().__init__(p, *args, **kwargs)
>
>    def __str__(self) -> str:
>        return str(self._original)
>```

I would now try to do this:

```
class PathParameter(Path):
    def __init__(self, p: str, *args, **kwargs) -> None:
        self._original = Path(p, *args, **kwargs)
        super().__init__(p, *args, **kwargs)

    def __str__(self) -> str:
        return str(self._original)
    def __getattr__(self, item) -> Any:
        result = super().__getattr__(item)
        if isinstance(result, Path):
            # we got a new path-like back
            new_path = PathParameter(result)
            new_path._original = self._original
            return new_path
        return result    
```

So, whenever a method does return a new `Path` (or subclass) we wrap that thing before returning it and maintain `original`. Otherwise we are transparent.
The second best option is a simple (data-) class to replace the tuple, and that's only intended to transport that information between CLI and command implementations (seems to be 2.).

In any case: I would be fine with post-poning the resolution of this issue - it's not urgent at all. That is: 1.) but don't close this issue.

**Comment by aqw** [comment]
This is functionally the same thing I was doing before, and will fail in the following situation:

```python
print(path / self.ANCHOR_FILE_NAME)
```

When a new object is created, it makes sure to retain `_original`. And `__str__()` returns `_original`. Thus only `path` is printed.

The problem comes down to:

* we want to retain this information
* if we do so, all future objects will retain either irrelevant or (even worse) incorrect information

These two are at odds with each other.

I agree that the tuple is weird, but creating an entire dataclass just to avoid a tuple also feels silly. `onyo_tree()` is unlikely to be used by anyone outside of `cli/tree.py`, but telling consumers that they must import a bespoke dataclass in order to pass in a string as a sidecar seems even sillier than saying "pass in an awkward tuple".

I will add a note in the source code, and then close this issue.

Ben knows that DataLad was dealing with similar problems, and he is interested in seeing how they addressed them. Perhaps their solution may be of relevance to us. At which point, this issue can be reopened or a new issue created.

**Comment by aqw** [comment]
Hah! And an idea strikes once the issue is closed. Reopening...
