### ISSUE TITLE
Provide hint on YAML for editors

### ISSUE THREAD

**Issue by bpoldrack** [psyinfra/onyo#644]
Either a leading `---` in asset files again (incl. temporary files) or a `.yaml` ending.

**Comment by TobiasKadelka** [comment]
If we decide to go only with `.yaml`, there is a need to modify `onyo cat` in parallel to show the `---` for readability when multiple files are `onyo cat`ed at the same time.

**Comment by TobiasKadelka** [comment]
I continued to reflect on this, and tested this: I tried to manually add the `---` with `onyo edit`, which is legal but of course does not work: 

```
(onyo_new) tkadelka in ~/inventory on git:master
❱ onyo edit spaces/14.6y/3040/display_dell_u2722de.BZPK5P3         
Effective changes:
Accept changes? (y)es / continue (e)diting / (s)kip asset / (a)bort command[Default: yes]y
Save changes? No discards all changes. (y/n) [Default: yes]y
```

It is weird that manually editing does not work as expected by a user, and it destroys the round trip mode we want to have and discussed in #159 and #261.

**Comment by aqw** [comment]
In my tests, the `---` was insufficient to hint `vim` that the file is YAML (though I could swear I've seen that before...). Ending the file in `.yaml` certainly did the trip (and I'm sure will too for other editors).

I do agree that having the document start `---` is helpful, especially for the `cat` usecase. I have opened #659 to track that.
