### ISSUE TITLE
New Feature: `onyo tree --directories`

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#677]
Currently, `onyo tree` outputs directories and assets. It would be nice to be able to generate a tree of just directories (equivalent of `tree -d`).

I see two ways of implementing this:
1) `onyo tree --no-assets` (`-A`): this will not print any assets (and thus logically exclude asset directories)
2) `onyo tree --directories` (`-d`): this will print only directories (and thus logically include asset directories)

`onyo tree` is not meant to be parsed or filtered by anything. So there's no need to build a clever filtering mechanism here.

I currently favor option 2. And it has the added bonus of matching `tree`'s syntax.

---
Note: I /really/ liked the idea of having a `--type` flag like (#676) and the default as `--type directory asset` (current behavior). But the entire point of `tree` is the directory structure. `--type asset` would not work; `directory` is not optional.

**Comment by bpoldrack** [comment]
I would lean towards 2., too.
