### ISSUE TITLE
New Feature: `onyo cat --flatten`

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#681]
This idea came out of the discussions around [onyo list-keys](#679). It is insufficient to cover all of the use-cases in #679, but I think it's an interesting idea in it's own right.

Currently, `onyo cat` simply returns the raw file.

I propose adding a `--flatten` flag (or another name, such as `--dot-notation`) that removes indentation from dictionaries and presents all keys in dot notation (see #668).

For example:
```
$ onyo cat shelf/desktop_dell_D11s.lmnop1234
---
type: desktop
make: dell
model:
    name: D11s
    year: 2017
serial: lmnop1234
inventory:
  fzj: 0123456
...
```
vs
```
$ onyo cat --flatten shelf/desktop_dell_D11s.lmnop1234
---
type: desktop
make: dell
model:
model.name: D11s
model.year: 2017
serial: lmnop1234
inventory:
inventory.fzj: 0123456
...
```

Currently, `onyo cat` uses `Path.read_text()`. Dot notation would require changing to loading and dumping the YAML. Care should be taken to make sure that everything is dumped identically to the raw file (comments, order, spacing, etc), just with dot notation. This could overlap with #261.

Open questions:
- is this feature useful?
- `--flatten` vs something with "dot notation" (e.g. `--dot-notation`) in the name?
- should keys of dicts be printed? (e.g. `inventory:`) This debate is part of the review of #668. As of this writing, `DotNotationWrapper().keys()` deems such keys as "structural" and does not return them.

**Comment by bpoldrack** [comment]
TBH: I don't really like that. A feature like that has little to do with `cat`. Smells more like a `onyo show` that can come with flattening, filtering, formatting options (like: Hey, give me a json representation of this).


Also: `model:` in the example isn't exactly "flattened".

**Comment by TobiasKadelka** [comment]
> is this feature useful?

I personally do not think so, based on my use cases so far. Once piping is in place, it might be useful for some situations, but even then I would either expect a command like Ben describes with `onyo show` or a `onyo get --flatten` flag to be able to provide such a functionality.

**Comment by aqw** [comment]
I also have soured on this idea. I will close this. if someone discovers a use-case, they are always welcome to re-open it.
