### ISSUE TITLE
`onyo new`: string are interpreted literally and not escaped

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#70]
When using `onyo new <dir>`, the directory name gets interpreted by the command line interface, and opens then this dialog:
```
<type>*:laptop
<make>*:lenovo
<model*>:T490
<serial*>:abc123
```
The dialog gets read with pythons function `str(input("<type>*"))`.

The CLI interprets the input different (`a\ a` as `a a`) then the input() function (`a\ a` as `a\ a`).

This is probably true for many characters and introduces different behaviour for both, which probably also includes some bugs (problems with quotes).

**Comment by aqw** [comment]
I don't see a clear description of the problem.

Input to `onyo new`'s prompts are treated literally --- and in my opinion they should be. Anything else is a deep rabbit hole that is not feasible, as each user's shell environment may be different.

I'm going to close this. If you feel there /is/ a clear misbehavior, please reopen and provide an example.
