### ISSUE TITLE
Design/New Feature: run multiple onyo commands in one call and one commit

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#734]
Yesterday I talked with Alex once again about the whole business with `onyo new`, `onyo set`, `onyo cat`, piping, `--yaml`, `--clone`, and how to operate recursively, whats with multifiles and asset dirs, you name it.

I think a lot of those discussions (not all -- but many) in regards to what makes most sense for most use-cases revolve around the idea "how to puzzle these 6 specific thoughts and actions into one single commit without rebasing etc" followed immediately by "what about the other use-cases then?" (this is all over-simplified, but I trust you all get what I am talking about, since it is one of our main topics the last weeks).

So I had a thought: currently we run commands like  `onyo new <args>` and `onyo set <args>`, they get executed in a row, one commit each; onyo parses the arguments and in `main.py` we do something like `args.run(args)`.

I began to wonder if not a lot of the very complex use-cases (and hopefully discussions around them) about using multiple flags, "what about order" etc could be reduced through doing instead something like these:

1. new group, or multiple things bought at once (line breaks only for readability)
```
onyo new --clone groups/dp/--d groups/other # new group starts, which is similar to existing one
     rm -rfd groups/other/Frank # new group has a member less, remove him
     mv --rename groups/other/Tobias groups/other/Jeremy # new members are named differently
     set --keys RAM=16G -d groups/new/Jeremy/Laptop # Ram for a laptop of a new member is different
```
2. new cluster added, but similar to old
```
onyo new --clone spaces/cluster/rack1 --recursive -d spaces/backup_cluster/rack1 # clone some infrastructure which is similar to existing
     set --template <template> -d spaces/backup_cluster/rack1/sub/dir/file # update just a specific part of the new cluster
```

In both cases the user gets then shown the diff, inventory operations, and so on, or simply errors if something does not work.

This would obviously mean some changes, like looping in main over `args.run()`, executing one of the sub-commands (new, mv, set) after another while working in memory on the same instance of Repository, and committing once in the end (if no errors occurred, user verified changes, etc like normal).

The win IMO are:
1. It is very easy to do very very complex things with as many clones, recursive sets, rm, and  so on, in a human readable and sequential way.
2. Things that can already achieved with complex commands can then also be done easier.
3. A lot of the questions "but how would a user achive task X if Y" would be very easy to answer. There is still a need to decide on the order of execution of flags (template, yaml, clone), default behavior (recursive or not?) on, but the negative costs for every decission would be reduced, because there is an easy alternative way to still do it in a single call if you know what to clone and how to adjust it then.
4. This could also reduce runtime for tests and some use-cases further, since information would just need to be read once, and objects don't have to be re-build as often.

**Comment by aqw** [comment]
Thanks for the suggestion, and thinking outside of the box. :-)

On reflection, I think this approach has multiple problems, beyond complexity.

I think it's a bit dangerous to bunch so many operations together, and will be difficult to build an effective summary of it.

I see two alternatives:
- use the onyo API in an ipython shell to do complex tasks
- an `onyo squash` command that squashes commits, builds a new commit subject, and appends the inventory operation records.

I'm going to close this issue as a "wontfix". But do want to thank you for taking the time to think outside the box and write this up. :-)
