### ISSUE TITLE
Bug: `onyo edit` does not print "Inventory Operations"

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#736]
The command `onyo edit` does not print the operations log that other committing commands print -- most notably`onyo set`, even though it does practically the same change on an asset.
```
❱ onyo edit repair/workbench/desktop_prodata_custom.2016-285                                    130 !
Effective changes:
--- /Users/tkadelka/inventory/repair/workbench/desktop_prodata_custom.2016-285
+++ /Users/tkadelka/inventory/repair/workbench/desktop_prodata_custom.2016-285
@@ -8,7 +8,7 @@
 inventory:
   fzj:
 
-junet_hostname: # ex mut019
+junet_hostname: asdf # ex mut019
 
 RAM:
 CPU:
Accept changes? (y)es / continue (e)diting / (s)kip asset / (a)bort command [Default: yes] y
Save changes? No discards all changes. (y/n) [Default: yes] y

❱ onyo set --keys junet_hostname=fdsa --asset repair/workbench/desktop_prodata_custom.2016-2
--- /Users/tkadelka/inventory/repair/workbench/desktop_prodata_custom.2016-2
+++ /Users/tkadelka/inventory/repair/workbench/desktop_prodata_custom.2016-2
@@ -8,7 +8,7 @@
 inventory:
   fzj:
 
-junet_hostname: asdf # ex mut019
+junet_hostname: fdsa # ex mut019
 
 RAM:
 CPU:

--- Inventory Operations ---
Modified assets:
- repair/workbench/desktop_prodata_custom.2016-2

Update assets? (y/n) [Default: yes] y
```

----

Losely related to `onyo edit` and it's behavior after I change an asset: if I use `onyo edit` to change a key that is used in the file name, it requires me to verify my changes seperately; the first time for changing the key in the asset and the second time for verifying the file name change.

```
❱ onyo edit repair/workbench/desktop_prodata_custom.2016-2                                        1 !
Effective changes:
--- /Users/tkadelka/inventory/repair/workbench/desktop_prodata_custom.2016-2
+++ /Users/tkadelka/inventory/repair/workbench/desktop_prodata_custom.2016-2
@@ -4,7 +4,7 @@
 model:
   name: custom
   year: 2016
-serial: 2016-2
+serial: 2016-285
 inventory:
   fzj:
 
/Users/tkadelka/inventory/repair/workbench/desktop_prodata_custom.2016-2 -> /Users/tkadelka/inventory/repair/workbench/desktop_prodata_custom.2016-285
Accept changes? (y)es / continue (e)diting / (s)kip asset / (a)bort command [Default: yes] y
Save changes? No discards all changes. (y/n) [Default: yes] y
```

I don't think this second case necessarily needs to be changed, the first behavior is the bigger problem.
But I want to share this case anyway, because together both these points make `onyo edit` feel weird and different than a user would assume.

**Comment by aqw** [comment]
I have opened #737 to show the Inventory Operations and address this issue.

The second issue you mention, I can't reproduce. There are always two prompts: one for the per-edit diff, and one final acceptance of all changes. This is the case whether it's one or many assets, and regardless if the key changed is part of the asset name.

Perhaps with the Inventory Operations printed, the behavior will seem more obvious.
