### ISSUE TITLE
Should `onyo edit` and `onyo init` accept multiple input-sources?

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#77]
While working on "checking all inputs before running the first command", I am wondering, if these two commands should accept multiple inputs.

`onyo init` could technically easily just run on multiple folders and create multiple onyo directories, like one can have any number of git repositories. This might be annoying when one wants to work  with `ONYO_REPOSITORY_DIR`, but in use cases where somebody wants not just track one inventory, but different things (or run for work and for home different onyo directories or something), it might be worth accepting multiple inputs, and check all of them, too, before creating the first one.

And for `onyo edit` it seems even more likely that somebody just wants to edit 2 files or more in a row, so it might be wished, that this command just opens them one after another.
The readme specifies just one input (without the `...` that for other commands state that multiple inputs are accepted), but I think this is at least worth a thought.

**Comment by aqw** [comment]
I can't imagine a sane situation where someone wants to `init` multiple repositories at once. Multiple arguments is almost certainly a mistake. I also cannot think of a sane way to handle `ONYO_REPOSITORY_DIR` while allowing such behavior. Does an argument plus `ONYO_REPOSITORY_DIR` mean `init` both? This path only leads to madness.

So IMO, `onyo init` should only accept one argument. (FTR: `git` allows limits `init` to only one dir).

As for `onyo edit`, I agree with you that someone could want to edit multiple files in succession. I don't know if/how `nano` handles such a situation, but I know `vim` allows it.

**Comment by TobiasKadelka** [comment]
Okey, for `onyo init` it stays with 1 argument.

For `onyo edit` I allow now multiple arguments, and if it is run for more then 1 file, they will be opened one after another. This is independent from the editor (even when some editor might just take 1 argument I think onyo should be consistently allowing multiple files), since I check the paths and run (vim just example) :
```
vim <file1>
vim <file2>
...
```
one after another in onyo.

**Comment by aqw** [comment]
> For `onyo edit` I allow now multiple arguments, and if it is run for more then 1 file, they will be opened one after another. This is independent from the editor (even when some editor might just take 1 argument I think onyo should be consistently allowing multiple files), since I check the paths and run (vim just example) :
> 
> ```
> vim <file1>
> vim <file2>
> ...
> ```
> 
> one after another in onyo.

This might indeed be the right way to do it (and keeps things agnostic of which `EDITOR` is in use), but a downside of this approach is that `vim` will not be able to share its buffer across files, making repetitive work much more difficult.

**Comment by aqw** [comment]
I have just tested `nano`, it also supports opening multiple files at once, and shares its buffer across files.

**Comment by TobiasKadelka** [comment]
Yes, but in case somebody would use a more exotic editor as default (that does not support multiple files) and also onyo, it will now still work instead of throwing an error, because of the way onyo calls the editor.

I think this makes more sense, because while onyo uses the default editor for changes, I don't think onyo should break/change behaviour because of it, at least in this case where it is easy to prevent.

**Comment by TobiasKadelka** [comment]
> This might indeed be the right way to do it (and keeps things agnostic of which `EDITOR` is in use), but a downside of this approach is that `vim` will not be able to share its buffer across files, making repetitive work much more difficult.

I thought about it again, and I think I can live with that, since `onyo set` and templating should make repetitive work easier again in the future. So I could live with that, rather then risking a change in behaviour between editors.

So in case we stay with this and live with the lost buffer, this issue can be closed, since the changes happended. 
Implementation: 22b7ce3950dcbe0a046ab7ea7e6f132c91d74bf6
Readme: 89f302ee27b1ab8b1134a739a89a22e241000096

Otherwise (and this would probably work, but I would not like this) we could implement an if/else exception for vi/vim and in that case call it like:
```
vim <file1> <file2> ...
```

**Comment by aqw** [comment]
Very good point wrt `onyo set`. This sounds good to me. :-)
