### ISSUE TITLE
Add `.onyoignore`

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#89]
`onyo fsck` respects the contents of the .gitignore file, and does not check files/folders specified there.
This is meant to allow non-onyo stuff in an onyo repository. But at the same time, when somebody wants to have the whole folder then shared with somebody else per git, it makes it impossible to push the non-onyo contents to git, too, without breaking onyo.

For this, there should be a`.onyoignore`, which allows to specify files which do not have to be onyo (e.g. files that are no valid asset files), but should be part of git.

**Comment by aqw** [comment]
I am not arguing against this approach, but I would like to make one clarification:

An entry in `.gitignore` does not prevent it from being tracked by git, pushed, etc. It's just that the pattern will not be monitored for unstaged changes. `git status` output (and I assume other commands) will ignore it. But an explicit `git add` on that file/folder works.

**Comment by aghisla** [comment]
Not sure if that has been superseded by more recent discussions+commits, but as a young git padawan I would keep it as simple as possible. Of course if not having a `.onyoignore` creates more trouble than having one, I'll learn what I need to.

**Comment by TobiasKadelka** [comment]
I think the primary use case for a `.onyoignore` not mentioned above would still be "ignoring" files for onyo that one wants to git track, e.g. recipes, pdfs or some other additional information that belongs to the inventory effort and might be best kept together with the actual hardware it belongs to.

So I think option 1 makes more sense, if we decide that this should not happen and the repositories should be as pur onyo as possible, but if we want to allow such scenarios it might be a situation were having a `.onyoignore` could kill both birds with the same stone.

**Comment by bpoldrack** [comment]
Implemented in PR #511: Add `.onyoignore` files anywhere and its patterns will apply to anything underneath that location. Exactly the same as `.gitignore` files (utilizing ``git check-ignore``).
