### ISSUE TITLE
Add option `-m` to commands to change default commit message

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#90]
Right now, commiting onyo commands have set commit messages (e.g. `delete asset(s)` or `initialize onyo repository`).
It should be possible to add a flag -m to these commands to overwrite the default message.

**Comment by aghisla** [comment]
+1 on this. Default messages should be clear enough on their own (see #122), but it may be occasionally necessary to add information.

**Comment by TobiasKadelka** [comment]
I am currently beginning to implement this, but want to already share this problem:

```
❱ onyo config -m "MSG" history.interactive "tig --follow"     
error: unknown switch `m'
usage: git config [<options>]

Config file location
    --global              use global config file
    --system              use system config file
    --local               use repository config file
    --worktree            use per-worktree config file
    -f, --file <file>     use given config file
    --blob <blob-id>      read config from given blob object

Action
[... etc, etc, the rest of `git config --help`. ]
```



In some way it seems to me like the config command (or rather argparser) seems to pass to much to git, instead of giving the text from `-m` to the  onyo command.
This makes not really sense to me, and I will try to understand the behavior and work around it, but I take this place to save the current information.

**Comment by aqw** [comment]
Well, `onyo config` is a bit of a special case. It's primarily meant to act as a wrapper around `git config`. That said, there's nothing that precludes us from intercepting `-m`. We already check for "forbidden" flags in `commands/config.py`. We could check for `-m`, strip it, and use the arg in the commit message.

**Comment by TobiasKadelka** [comment]
Yes, that is true.

Another special case would probably be `onyo init`, since it calls `Repo.init()`, but never `Repo.commit()`, for obvious reasons.
For this, I will probably have to add an optional argument to the repo-class.

**Comment by aqw** [comment]
I comfortable with `onyo init` being an exception. It's literally used once, and someone can `git commit --amend` if they desperately want to change it.
